INSERT INTO municipalities(code, name, gentilic, state) VALUES (2100055, "Açailândia", "açailandense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2100105, "Afonso Cunha", "afonso-cunhense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2100154, "Água Doce do Maranhão", "aguadocense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2100204, "Alcântara", "alcantarense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2100303, "Aldeias Altas", "aldeias-altense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2100402, "Altamira do Maranhão", "altamirense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2100436, "Alto Alegre do Maranhão", "alto-alegrense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2100477, "Alto Alegre do Pindaré", "alto-alegrense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2100501, "Alto Parnaíba", "alto-parnaibano", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2100550, "Amapá do Maranhão", "amapaense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2100600, "Amarante do Maranhão", "amarantino", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2100709, "Anajatuba", "anajatubense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2100808, "Anapurus", "anapuruense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2100832, "Apicum-Açu", "apicum-açuense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2100873, "Araguanã", "araguanaense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2100907, "Araioses", "araiosense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2100956, "Arame", "aramense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2101004, "Arari", "arariense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2101103, "Axixá", "axixaense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2101202, "Bacabal", "bacabalense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2101251, "Bacabeira", "bacabeirense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2101301, "Bacuri", "bacuriense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2101350, "Bacurituba", "bacuritubense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2101400, "Balsas", "balsense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2101509, "Barão de Grajaú", "baronense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2101608, "Barra do Corda", "barra-cordense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2101707, "Barreirinhas", "barreirinhense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2101772, "Bela Vista do Maranhão", "bela-vistense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2101731, "Belágua", "belaguaense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2101806, "Benedito Leite", "beneleitense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2101905, "Bequimão", "bequimãoense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2101939, "Bernardo do Mearim", "bernardense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2101970, "Boa Vista do Gurupi", "boa-vistense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2102002, "Bom Jardim", "bom-jardinense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2102036, "Bom Jesus das Selvas", "bom-jesuense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2102077, "Bom Lugar", "bom-lugarense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2102101, "Brejo", "brejense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2102150, "Brejo de Areia", "brejareiense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2102200, "Buriti", "buritiense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2102309, "Buriti Bravo", "buriti-bravense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2102325, "Buriticupu", "buriticupuense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2102358, "Buritirana", "buritiranense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2102374, "Cachoeira Grande", "cachoeirense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2102408, "Cajapió", "cajapioense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2102507, "Cajari", "cajariense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2102556, "Campestre do Maranhão", "campestrino", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2102606, "Cândido Mendes", "cândido-mendense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2102705, "Cantanhede", "cantanhedense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2102754, "Capinzal do Norte", "capinzalense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2102804, "Carolina", "carolinense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2102903, "Carutapera", "carutaperense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2103000, "Caxias", "caxiense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2103109, "Cedral", "cedralense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2103125, "Central do Maranhão", "centralense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2103158, "Centro do Guilherme", "centroguilhermense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2103174, "Centro Novo do Maranhão", "centronovense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2103208, "Chapadinha", "chapadinhense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2103257, "Cidelândia", "cidelandense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2103307, "Codó", "codoense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2103406, "Coelho Neto", "coelho-netense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2103505, "Colinas", "colinense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2103554, "Conceição do Lago-Açu", "lagoaçuense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2103604, "Coroatá", "coroataense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2103703, "Cururupu", "cururupuense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2103752, "Davinópolis", "davinopolitano", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2103802, "Dom Pedro", "dom-pedrense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2103901, "Duque Bacelar", "bacelarense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2104008, "Esperantinópolis", "esperantinopense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2104057, "Estreito", "estreitense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2104073, "Feira Nova do Maranhão", "nova-feirense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2104081, "Fernando Falcão", "fernandense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2104099, "Formosa da Serra Negra", "formosense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2104107, "Fortaleza dos Nogueiras", "fortalezense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2104206, "Fortuna", "fortunense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2104305, "Godofredo Viana", "godofredense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2104404, "Gonçalves Dias", "gonçalvino", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2104503, "Governador Archer", "archense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2104552, "Governador Edison Lobão", "edison-lobense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2104602, "Governador Eugênio Barros", "eugênio-barrense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2104628, "Governador Luiz Rocha", "luiz-rochense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2104651, "Governador Newton Bello", "newton-belense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2104677, "Governador Nunes Freire", "nunes-freirense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2104701, "Graça Aranha", "graçaranhense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2104800, "Grajaú", "grajauense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2104909, "Guimarães", "vimaranense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2105005, "Humberto de Campos", "humbertoense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2105104, "Icatu", "icatuense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2105153, "Igarapé do Meio", "igarapeense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2105203, "Igarapé Grande", "igarapé-grandense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2105302, "Imperatriz", "imperatrizense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2105351, "Itaipava do Grajaú", "itaipavense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2105401, "Itapecuru Mirim", "itapecuruense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2105427, "Itinga do Maranhão", "itinguense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2105450, "Jatobá", "jatobaense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2105476, "Jenipapo dos Vieiras", "jenipapoense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2105500, "João Lisboa", "joão-lisboense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2105609, "Joselândia", "joselandense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2105658, "Junco do Maranhão", "juncoense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2105708, "Lago da Pedra", "lago-pedrense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2105807, "Lago do Junco", "juncoense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2105948, "Lago dos Rodrigues", "lago-rodriguense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2105906, "Lago Verde", "lago-verdense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2105922, "Lagoa do Mato", "lagoense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2105963, "Lagoa Grande do Maranhão", "lagoa-grandense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2105989, "Lajeado Novo", "lajeadense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2106003, "Lima Campos", "lima-campense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2106102, "Loreto", "lorentense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2106201, "Luís Domingues", "luís-dominguense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2106300, "Magalhães de Almeida", "magalhense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2106326, "Maracaçumé", "maracaçumeense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2106359, "Marajá do Sena", "marajaense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2106375, "Maranhãozinho", "maranhãozinense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2106409, "Mata Roma", "mata-romense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2106508, "Matinha", "matinhense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2106607, "Matões", "matoense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2106631, "Matões do Norte", "norte-matõense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2106672, "Milagres do Maranhão", "milagrense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2106706, "Mirador", "miradoense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2106755, "Miranda do Norte", "mirandense-do-norte", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2106805, "Mirinzal", "mirinzalense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2106904, "Monção", "monçonense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2107001, "Montes Altos", "monte-altense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2107100, "Morros", "morroense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2107209, "Nina Rodrigues", "ninense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2107258, "Nova Colinas", "nova-colinense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2107308, "Nova Iorque", "nova-iorquino", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2107357, "Nova Olinda do Maranhão", "novaolindense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2107407, "Olho d'Água das Cunhãs", "olho-daguense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2107456, "Olinda Nova do Maranhão", "olindense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2107506, "Paço do Lumiar", "luminense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2107605, "Palmeirândia", "palmeirandense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2107704, "Paraibano", "paraibanense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2107803, "Parnarama", "parnaramense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2107902, "Passagem Franca", "passagense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2108009, "Pastos Bons", "pastos-bonense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2108058, "Paulino Neves", "paulinoense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2108108, "Paulo Ramos", "paulo-ramense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2108207, "Pedreiras", "pedreirense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2108256, "Pedro do Rosário", "pedro-rosariense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2108306, "Penalva", "penalvense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2108405, "Peri Mirim", "peri-miriense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2108454, "Peritoró", "peritoroense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2108504, "Pindaré-Mirim", "pindareense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2108603, "Pinheiro", "pinheirense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2108702, "Pio XII", "piodocense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2108801, "Pirapemas", "pirapemense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2108900, "Poção de Pedras", "poção-pedrense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2109007, "Porto Franco", "porto-franquino", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2109056, "Porto Rico do Maranhão", "porto-riquense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2109106, "Presidente Dutra", "presidutrense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2109205, "Presidente Juscelino", "juscelinense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2109239, "Presidente Médici", "medicense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2109270, "Presidente Sarney", "sarneyense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2109304, "Presidente Vargas", "presidentino", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2109403, "Primeira Cruz", "primeira-cruzense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2109452, "Raposa", "raposense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2109502, "Riachão", "riachãoense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2109551, "Ribamar Fiquene", "fiquenense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2109601, "Rosário", "rosariense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2109700, "Sambaíba", "sambaibense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2109759, "Santa Filomena do Maranhão", "santa-filomenense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2109809, "Santa Helena", "santa-helenense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2109908, "Santa Inês", "santa-inesense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2110005, "Santa Luzia", "santa-luziense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2110039, "Santa Luzia do Paruá", "santa-luziense-do-paruá", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2110104, "Santa Quitéria do Maranhão", "quiteriense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2110203, "Santa Rita", "santa-ritense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2110237, "Santana do Maranhão", "santanense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2110278, "Santo Amaro do Maranhão", "santamarense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2110302, "Santo Antônio dos Lopes", "santo-antoense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2110401, "São Benedito do Rio Preto", "são-beneditense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2110500, "São Bento", "são-bentuense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2110609, "São Bernardo", "bernardense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2110658, "São Domingos do Azeitão", "são-dominguense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2110708, "São Domingos do Maranhão", "são-dominguense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2110807, "São Félix de Balsas", "são-felense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2110856, "São Francisco do Brejão", "brejãoense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2110906, "São Francisco do Maranhão", "são-franciscano", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2111003, "São João Batista", "juanino ou joanino", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2111029, "São João do Carú", "caruense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2111052, "São João do Paraíso", "paraisense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2111078, "São João do Soter", "sotense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2111102, "São João dos Patos", "patoense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2111201, "São José de Ribamar", "ribamarense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2111250, "São José dos Basílios", "basiliense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2111300, "São Luís", "são-luisense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2111409, "São Luís Gonzaga do Maranhão", "gonzaguense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2111508, "São Mateus do Maranhão", "são-mateuense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2111532, "São Pedro da Água Branca", "agua-braquense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2111573, "São Pedro dos Crentes", "são-pedrense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2111607, "São Raimundo das Mangabeiras", "mangabeirense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2111631, "São Raimundo do Doca Bezerra", "são-raimundense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2111672, "São Roberto", "são-robertense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2111706, "São Vicente Ferrer", "vicentino", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2111722, "Satubinha", "satubinhense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2111748, "Senador Alexandre Costa", "alexandrecostense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2111763, "Senador La Rocque", "laroquense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2111789, "Serrano do Maranhão", "serranense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2111805, "Sítio Novo", "sitio-novense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2111904, "Sucupira do Norte", "sucupirense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2111953, "Sucupira do Riachão", "sucupirense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2112001, "Tasso Fragoso", "fragosense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2112100, "Timbiras", "timbirense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2112209, "Timon", "timonense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2112233, "Trizidela do Vale", "trizidelense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2112274, "Tufilândia", "tufilandense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2112308, "Tuntum", "tuntuense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2112407, "Turiaçu", "turiense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2112456, "Turilândia", "turilandense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2112506, "Tutóia", "tutoiense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2112605, "Urbano Santos", "urbano-santense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2112704, "Vargem Grande", "vargem-grandense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2112803, "Viana", "vianense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2112852, "Vila Nova dos Martírios", "vila-novense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2112902, "Vitória do Mearim", "vitoriense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2113009, "Vitorino Freire", "vitorinense", 21);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2114007, "Zé Doca", "zé-doquense", 21);