INSERT INTO municipalities(code, name, gentilic, state) VALUES (2600054, "Abreu e Lima", "abreu-limense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2600104, "Afogados da Ingazeira", "afogadense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2600203, "Afrânio", "afraniense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2600302, "Agrestina", "agrestinense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2600401, "Água Preta", "água-pretense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2600500, "Águas Belas", "águas-belense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2600609, "Alagoinha", "alagoinhense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2600708, "Aliança", "aliancense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2600807, "Altinho", "altinense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2600906, "Amaraji", "amarajinense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2601003, "Angelim", "angelinense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2601052, "Araçoiaba", "araçoiabense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2601102, "Araripina", "araripinense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2601201, "Arcoverde", "arcoverdense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2601300, "Barra de Guabiraba", "guabirabense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2601409, "Barreiros", "barreirense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2601508, "Belém de Maria", "belenense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2601607, "Belém do São Francisco", "belenense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2601706, "Belo Jardim", "belo-jardinense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2601805, "Betânia", "betaniense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2601904, "Bezerros", "bezerrense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2602001, "Bodocó", "bodocense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2602100, "Bom Conselho", "conselhense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2602209, "Bom Jardim", "bom-jardinense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2602308, "Bonito", "bonitense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2602407, "Brejão", "brejonense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2602506, "Brejinho", "brejinhense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2602605, "Brejo da Madre de Deus", "brejense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2602704, "Buenos Aires", "buenairense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2602803, "Buíque", "buiquense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2602902, "Cabo de Santo Agostinho", "cabense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2603009, "Cabrobó", "cabroboense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2603108, "Cachoeirinha", "cachoeirinhense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2603207, "Caetés", "caeteense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2603306, "Calçado", "calçadense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2603405, "Calumbi", "calumbiense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2603454, "Camaragibe", "camaragibense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2603504, "Camocim de São Félix", "camocinense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2603603, "Camutanga", "camutanguense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2603702, "Canhotinho", "canhotinhense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2603801, "Capoeiras", "capoeirense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2603900, "Carnaíba", "carnaibano", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2603926, "Carnaubeira da Penha", "carnaubeirense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2604007, "Carpina", "carpinense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2604106, "Caruaru", "caruaruense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2604155, "Casinhas", "casinhense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2604205, "Catende", "catendense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2604304, "Cedro", "cedrense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2604403, "Chã de Alegria", "alegriense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2604502, "Chã Grande", "chã-grandense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2604601, "Condado", "condadense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2604700, "Correntes", "correntense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2604809, "Cortês", "cortesense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2604908, "Cumaru", "cumaruense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2605004, "Cupira", "cupirense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2605103, "Custódia", "custodiense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2605152, "Dormentes", "dormentense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2605202, "Escada", "escadense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2605301, "Exu", "exuense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2605400, "Feira Nova", "feira-novense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2605459, "Fernando de Noronha", "noronhense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2605509, "Ferreiros", "ferreirense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2605608, "Flores", "florense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2605707, "Floresta", "florestano", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2605806, "Frei Miguelinho", "frei-miguelinhense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2605905, "Gameleira", "gameleirense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2606002, "Garanhuns", "garanhuense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2606101, "Glória do Goitá", "gloriense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2606200, "Goiana", "goianense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2606309, "Granito", "granitense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2606408, "Gravatá", "gravataense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2606507, "Iati", "iatiense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2606606, "Ibimirim", "ibimiriense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2606705, "Ibirajuba", "ibirajubense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2606804, "Igarassu", "igarassuano", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2606903, "Iguaracy", "iguaraciense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2607604, "Ilha de Itamaracá", "itamaracaense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2607000, "Inajá", "inajaense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2607109, "Ingazeira", "ingazeirense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2607208, "Ipojuca", "ipojuquense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2607307, "Ipubi", "ipubiense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2607406, "Itacuruba", "itacurubense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2607505, "Itaíba", "itaibense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2607653, "Itambé", "itambeense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2607703, "Itapetim", "itapetinense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2607752, "Itapissuma", "itapissumense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2607802, "Itaquitinga", "itaquitinguense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2607901, "Jaboatão dos Guararapes", "jaboatãoense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2607950, "Jaqueira", "jaqueirense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2608008, "Jataúba", "jataubense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2608057, "Jatobá", "jatobaense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2608107, "João Alfredo", "alfredense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2608206, "Joaquim Nabuco", "nabuquense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2608255, "Jucati", "jucatiense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2608305, "Jupi", "jupiense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2608404, "Jurema", "juremense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2608503, "Lagoa de Itaenga", "itaenguense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2608453, "Lagoa do Carro", "lagoense do carro", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2608602, "Lagoa do Ouro", "lagoa-do-ourense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2608701, "Lagoa dos Gatos", "lagoense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2608750, "Lagoa Grande", "lagoa-grandense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2608800, "Lajedo", "lajedense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2608909, "Limoeiro", "limoeirense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2609006, "Macaparana", "macaparanense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2609105, "Machados", "machadense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2609154, "Manari", "manariense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2609204, "Maraial", "maraialense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2609303, "Mirandiba", "mirandibense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2614303, "Moreilândia", "moreirense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2609402, "Moreno", "morenense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2609501, "Nazaré da Mata", "nazareno", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2609600, "Olinda", "olindense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2609709, "Orobó", "orobense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2609808, "Orocó", "orocoense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2609907, "Ouricuri", "ouricuriense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2610004, "Palmares", "palmarense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2610103, "Palmeirina", "palmeirinense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2610202, "Panelas", "panelense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2610301, "Paranatama", "paranatamense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2610400, "Parnamirim", "parnamirinense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2610509, "Passira", "passirense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2610608, "Paudalho", "paudalhense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2610707, "Paulista", "paulistano", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2610806, "Pedra", "pedrense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2610905, "Pesqueira", "pesqueirense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2611002, "Petrolândia", "petrolandense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2611101, "Petrolina", "petrolinense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2611200, "Poção", "poçãoense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2611309, "Pombos", "pomboense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2611408, "Primavera", "primaverense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2611507, "Quipapá", "quipapaense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2611533, "Quixaba", "quixabense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2611606, "Recife", "recifense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2611705, "Riacho das Almas", "riachense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2611804, "Ribeirão", "ribeirãoense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2611903, "Rio Formoso", "rio-formosense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2612000, "Sairé", "saireense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2612109, "Salgadinho", "salgadinense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2612208, "Salgueiro", "salgueirense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2612307, "Saloá", "saloaense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2612406, "Sanharó", "sanharoense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2612455, "Santa Cruz", "santacruzense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2612471, "Santa Cruz da Baixa Verde", "santacruzense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2612505, "Santa Cruz do Capibaribe", "santa-cruzense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2612554, "Santa Filomena", "filomense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2612604, "Santa Maria da Boa Vista", "boa-vistense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2612703, "Santa Maria do Cambucá", "santa-mariense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2612802, "Santa Terezinha", "santa-terezinhense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2612901, "São Benedito do Sul", "são-beneditense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2613008, "São Bento do Una", "são-bentense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2613107, "São Caitano", "são-caitanense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2613206, "São João", "são-joanense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2613305, "São Joaquim do Monte", "são-joaquinense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2613404, "São José da Coroa Grande", "são-josé-coroa-grandense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2613503, "São José do Belmonte", "belmontense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2613602, "São José do Egito", "egipsiense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2613701, "São Lourenço da Mata", "são-lourensense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2613800, "São Vicente Ferrer", "são-vicentino", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2613909, "Serra Talhada", "serra-talhadense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2614006, "Serrita", "serritense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2614105, "Sertânia", "sertaniense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2614204, "Sirinhaém", "sirinhaense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2614402, "Solidão", "solidanense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2614501, "Surubim", "surubinense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2614600, "Tabira", "tabirense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2614709, "Tacaimbó", "tacaimboense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2614808, "Tacaratu", "tacaratuense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2614857, "Tamandaré", "tamandareense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2615003, "Taquaritinga do Norte", "taquaritinguense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2615102, "Terezinha", "terezinhense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2615201, "Terra Nova", "terra-novense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2615300, "Timbaúba", "timbaubense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2615409, "Toritama", "toritamense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2615508, "Tracunhaém", "tracunhaense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2615607, "Trindade", "trindadense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2615706, "Triunfo", "triunfense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2615805, "Tupanatinga", "tupanatinguense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2615904, "Tuparetama", "tuparetamense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2616001, "Venturosa", "venturosense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2616100, "Verdejante", "verdejantense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2616183, "Vertente do Lério", "vertentense do lério", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2616209, "Vertentes", "vertentense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2616308, "Vicência", "vicenciense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2616407, "Vitória de Santo Antão", "vitoriense", 26);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2616506, "Xexéu", "xexeuense", 26);