INSERT INTO municipalities(code, name, gentilic, state) VALUES (2800100, "Amparo de São Francisco", "amparense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2800209, "Aquidabã", "aquidabãense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2800308, "Aracaju", "aracajuano", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2800407, "Arauá", "arauaense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2800506, "Areia Branca", "areia-branquense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2800605, "Barra dos Coqueiros", "barra-coqueirense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2800670, "Boquim", "boquinense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2800704, "Brejo Grande", "brejo-grandense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2801009, "Campo do Brito", "campo-britense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2801108, "Canhoba", "canhobense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2801207, "Canindé de São Francisco", "canindense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2801306, "Capela", "capelense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2801405, "Carira", "carirense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2801504, "Carmópolis", "carmopolense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2801603, "Cedro de São João", "cedrense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2801702, "Cristinápolis", "cristinapolense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2801900, "Cumbe", "cumbense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2802007, "Divina Pastora", "divina-pastorense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2802106, "Estância", "estanciano", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2802205, "Feira Nova", "feira-novense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2802304, "Frei Paulo", "frei-paulense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2802403, "Gararu", "gararuense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2802502, "General Maynard", "mainardense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2802601, "Gracho Cardoso", "gracho-cardosense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2802700, "Ilha das Flores", "ilha-florense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2802809, "Indiaroba", "indiarobense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2802908, "Itabaiana", "itabaianense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2803005, "Itabaianinha", "itabaianinhense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2803104, "Itabi", "itabiense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2803203, "Itaporanga d'Ajuda", "itaporanguense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2803302, "Japaratuba", "japaratubense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2803401, "Japoatã", "japoatãnense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2803500, "Lagarto", "lagartense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2803609, "Laranjeiras", "laranjeirense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2803708, "Macambira", "macambirense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2803807, "Malhada dos Bois", "malhadense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2803906, "Malhador", "malhadorense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2804003, "Maruim", "maruinense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2804102, "Moita Bonita", "moita-bonitense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2804201, "Monte Alegre de Sergipe", "monte-alegrense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2804300, "Muribeca", "muribequense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2804409, "Neópolis", "neopolense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2804458, "Nossa Senhora Aparecida", "aparecidense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2804508, "Nossa Senhora da Glória", "glorense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2804607, "Nossa Senhora das Dores", "dorense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2804706, "Nossa Senhora de Lourdes", "lourdense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2804805, "Nossa Senhora do Socorro", "socorrense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2804904, "Pacatuba", "pacatubense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2805000, "Pedra Mole", "pedra-molense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2805109, "Pedrinhas", "pedrinhense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2805208, "Pinhão", "pinhãoense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2805307, "Pirambu", "pirambuense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2805406, "Poço Redondo", "poço-redondense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2805505, "Poço Verde", "poço-verdense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2805604, "Porto da Folha", "porto-folhense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2805703, "Propriá", "propriaense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2805802, "Riachão do Dantas", "riachãoense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2805901, "Riachuelo", "riachuelense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2806008, "Ribeirópolis", "ribeiropolense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2806107, "Rosário do Catete", "rosarense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2806206, "Salgado", "salgadense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2806305, "Santa Luzia do Itanhy", "santa-luziense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2806503, "Santa Rosa de Lima", "santa-rosense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2806404, "Santana do São Francisco", "santanense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2806602, "Santo Amaro das Brotas", "brotense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2806701, "São Cristóvão", "são-cristóvense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2806800, "São Domingos", "são-dominguense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2806909, "São Francisco", "são-francisquense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2807006, "São Miguel do Aleixo", "aleixense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2807105, "Simão Dias", "simão-diense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2807204, "Siriri", "siririense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2807303, "Telha", "telhense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2807402, "Tobias Barreto", "tobiense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2807501, "Tomar do Geru", "geruense", 28);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (2807600, "Umbaúba", "umbaubense", 28);