INSERT INTO municipalities(code, name, gentilic, state) VALUES (3100104, "Abadia dos Dourados", "abadiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3100203, "Abaeté", "abaetense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3100302, "Abre Campo", "abre-campense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3100401, "Acaiaca", "acaiaquense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3100500, "Açucena", "açucenense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3100609, "Água Boa", "água-boense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3100708, "Água Comprida", "água-compridense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3100807, "Aguanil", "aguanilense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3100906, "Águas Formosas", "águas-formosense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3101003, "Águas Vermelhas", "águas-vermelhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3101102, "Aimorés", "aimorense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3101201, "Aiuruoca", "aiuruocano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3101300, "Alagoa", "alagoense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3101409, "Albertina", "albertinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3101508, "Além Paraíba", "além-paraíbano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3101607, "Alfenas", "alfenense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3101631, "Alfredo Vasconcelos", "vasconcelense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3101706, "Almenara", "almenarense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3101805, "Alpercata", "alpercatense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3101904, "Alpinópolis", "alpinopolense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3102001, "Alterosa", "alterosense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3102050, "Alto Caparaó", "alto caparoense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3153509, "Alto Jequitibá", "jequitibaense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3102100, "Alto Rio Doce", "alto-rio-docense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3102209, "Alvarenga", "alvarenguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3102308, "Alvinópolis", "alvinopolense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3102407, "Alvorada de Minas", "alvoradense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3102506, "Amparo do Serra", "serrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3102605, "Andradas", "andradense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3102803, "Andrelândia", "andrelandense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3102852, "Angelândia", "angelandense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3102902, "Antônio Carlos", "antônio-carlense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3103009, "Antônio Dias", "antônio-diense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3103108, "Antônio Prado de Minas", "pradense-de-minas", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3103207, "Araçaí", "araçaiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3103306, "Aracitaba", "aracitabense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3103405, "Araçuaí", "araçuaiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3103504, "Araguari", "araguarino", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3103603, "Arantina", "arantinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3103702, "Araponga", "araponguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3103751, "Araporã", "araporense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3103801, "Arapuá", "arapuaense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3103900, "Araújos", "araujense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3104007, "Araxá", "araxaense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3104106, "Arceburgo", "arceburguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3104205, "Arcos", "arcoense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3104304, "Areado", "areadense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3104403, "Argirita", "argiritense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3104452, "Aricanduva", "aricanduvense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3104502, "Arinos", "arinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3104601, "Astolfo Dutra", "astolfo-dutrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3104700, "Ataléia", "ataleiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3104809, "Augusto de Lima", "augusto-limense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3104908, "Baependi", "baependiano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3105004, "Baldim", "baldinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3105103, "Bambuí", "bambuiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3105202, "Bandeira", "bandeirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3105301, "Bandeira do Sul", "bandeirante-do-sul", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3105400, "Barão de Cocais", "cocaiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3105509, "Barão de Monte Alto", "monte-altense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3105608, "Barbacena", "barbacenense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3105707, "Barra Longa", "barra-longuense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3105905, "Barroso", "barrosense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3106002, "Bela Vista de Minas", "bela-vistano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3106101, "Belmiro Braga", "belmirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3106200, "Belo Horizonte", "belo-horizontino", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3106309, "Belo Oriente", "belo-orientino", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3106408, "Belo Vale", "belo-valense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3106507, "Berilo", "berilense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3106655, "Berizal", "berizalense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3106606, "Bertópolis", "bertopolitano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3106705, "Betim", "betinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3106804, "Bias Fortes", "bias-fortense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3106903, "Bicas", "biquense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3107000, "Biquinhas", "biquinhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3107109, "Boa Esperança", "esperancense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3107208, "Bocaina de Minas", "bocainense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3107307, "Bocaiúva", "bocaiuvense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3107406, "Bom Despacho", "bom-despachense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3107505, "Bom Jardim de Minas", "bom-jardinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3107604, "Bom Jesus da Penha", "bom-jesuense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3107703, "Bom Jesus do Amparo", "bom-jesuense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3107802, "Bom Jesus do Galho", "bom-jesuense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3107901, "Bom Repouso", "bom-repousense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3108008, "Bom Sucesso", "bom-sucessense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3108107, "Bonfim", "bonfinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3108206, "Bonfinópolis de Minas", "bonfinopolitano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3108255, "Bonito de Minas", "bonitense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3108305, "Borda da Mata", "borda-matense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3108404, "Botelhos", "botelhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3108503, "Botumirim", "botumiriense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3108701, "Brás Pires", "brás-pirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3108552, "Brasilândia de Minas", "brasilandense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3108602, "Brasília de Minas", "brasilminense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3108800, "Braúnas", "braunense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3108909, "Brazópolis", "brasopolense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3109006, "Brumadinho", "brumadinhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3109105, "Bueno Brandão", "bueno-brandense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3109204, "Buenópolis", "buenopolitano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3109253, "Bugre", "bugrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3109303, "Buritis", "buritisense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3109402, "Buritizeiro", "buritizeirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3109451, "Cabeceira Grande", "cabeceirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3109501, "Cabo Verde", "cabo-verdense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3109600, "Cachoeira da Prata", "cachoeirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3109709, "Cachoeira de Minas", "cachoeirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3102704, "Cachoeira de Pajeú", "cachoeirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3109808, "Cachoeira Dourada", "cachoeirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3109907, "Caetanópolis", "caetanopolitano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3110004, "Caeté", "caeteense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3110103, "Caiana", "caianense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3110202, "Cajuri", "cajuriense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3110301, "Caldas", "caldense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3110400, "Camacho", "camachense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3110509, "Camanducaia", "camanducaiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3110608, "Cambuí", "cambuiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3110707, "Cambuquira", "cambuquirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3110806, "Campanário", "campanarense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3110905, "Campanha", "campanhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3111002, "Campestre", "campestrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3111101, "Campina Verde", "campina-verdense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3111150, "Campo Azul", "campoazulense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3111200, "Campo Belo", "campo-belense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3111309, "Campo do Meio", "campo-meiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3111408, "Campo Florido", "campo-floridense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3111507, "Campos Altos", "campos-altense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3111606, "Campos Gerais", "campos-geraiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3111903, "Cana Verde", "cana-verdense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3111705, "Canaã", "canaãense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3111804, "Canápolis", "canapolense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3112000, "Candeias", "candeense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3112059, "Cantagalo", "cantagalense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3112109, "Caparaó", "caparaoense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3112208, "Capela Nova", "capela-novense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3112307, "Capelinha", "capelinhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3112406, "Capetinga", "capetinguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3112505, "Capim Branco", "capim-branquense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3112604, "Capinópolis", "capinopolino", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3112653, "Capitão Andrade", "capitão andradense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3112703, "Capitão Enéas", "capitão-eneense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3112802, "Capitólio", "capitolino", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3112901, "Caputira", "caputirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3113008, "Caraí", "caraiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3113107, "Caranaíba", "caranaibense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3113206, "Carandaí", "carandaiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3113305, "Carangola", "carangolense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3113404, "Caratinga", "caratinguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3113503, "Carbonita", "carbonitense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3113602, "Careaçu", "careaçuense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3113701, "Carlos Chagas", "carlos-chaguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3113800, "Carmésia", "carmesense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3113909, "Carmo da Cachoeira", "carmo-cachoeirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3114006, "Carmo da Mata", "carmense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3114105, "Carmo de Minas", "carmoense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3114204, "Carmo do Cajuru", "cajuruense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3114303, "Carmo do Paranaíba", "carmense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3114402, "Carmo do Rio Claro", "carmelitano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3114501, "Carmópolis de Minas", "carmopolitano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3114550, "Carneirinho", "carneirinhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3114600, "Carrancas", "carranquense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3114709, "Carvalhópolis", "carvalhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3114808, "Carvalhos", "carvalhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3114907, "Casa Grande", "casa-grandense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3115003, "Cascalho Rico", "cascalho-riquense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3115102, "Cássia", "cassiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3115300, "Cataguases", "cataguasense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3115359, "Catas Altas", "catas-altense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3115409, "Catas Altas da Noruega", "catas-altense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3115458, "Catuji", "catujiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3115474, "Catuti", "catutiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3115508, "Caxambu", "caxambuense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3115607, "Cedro do Abaeté", "cedrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3115706, "Central de Minas", "centralense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3115805, "Centralina", "centralinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3115904, "Chácara", "chacarense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3116001, "Chalé", "chaleense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3116100, "Chapada do Norte", "chapadense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3116159, "Chapada Gaúcha", "chapadense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3116209, "Chiador", "chiadorense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3116308, "Cipotânea", "cipotanense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3116407, "Claraval", "claravalense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3116506, "Claro dos Poções", "claro-pocense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3116605, "Cláudio", "claudiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3116704, "Coimbra", "coimbraense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3116803, "Coluna", "colunense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3116902, "Comendador Gomes", "comendadorense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3117009, "Comercinho", "comerciense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3117108, "Conceição da Aparecida", "aparecidense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3115201, "Conceição da Barra de Minas", "conceicionense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3117306, "Conceição das Alagoas", "garimpense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3117207, "Conceição das Pedras", "pedrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3117405, "Conceição de Ipanema", "ipanemense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3117504, "Conceição do Mato Dentro", "conceicionense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3117603, "Conceição do Pará", "conceição-paraense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3117702, "Conceição do Rio Verde", "conceicionense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3117801, "Conceição dos Ouros", "ourense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3117836, "Cônego Marinho", "cônego marinhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3117876, "Confins", "confinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3117900, "Congonhal", "congonhalense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3118007, "Congonhas", "congonhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3118106, "Congonhas do Norte", "congonhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3118205, "Conquista", "conquistense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3118304, "Conselheiro Lafaiete", "lafaietense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3118403, "Conselheiro Pena", "conselheiro-penense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3118502, "Consolação", "consolense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3118601, "Contagem", "contagense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3118700, "Coqueiral", "coqueirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3118809, "Coração de Jesus", "corjesuense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3118908, "Cordisburgo", "cordisburguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3119005, "Cordislândia", "cordislandense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3119104, "Corinto", "corintiano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3119203, "Coroaci", "coroaciense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3119302, "Coromandel", "coromandelense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3119401, "Coronel Fabriciano", "fabricianense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3119500, "Coronel Murta", "murtense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3119609, "Coronel Pacheco", "pachequense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3119708, "Coronel Xavier Chaves", "xavierense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3119807, "Córrego Danta", "córrego-dantense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3119906, "Córrego do Bom Jesus", "correguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3119955, "Córrego Fundo", "corregofundense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3120003, "Córrego Novo", "córrego-novense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3120102, "Couto de Magalhães de Minas", "couto-magalhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3120151, "Crisólita", "crisolitense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3120201, "Cristais", "cristalense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3120300, "Cristália", "cristalense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3120409, "Cristiano Otoni", "cristianense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3120508, "Cristina", "cristinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3120607, "Crucilândia", "crucilandense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3120706, "Cruzeiro da Fortaleza", "cruzeirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3120805, "Cruzília", "cruzilense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3120839, "Cuparaque", "cuparaquense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3120870, "Curral de Dentro", "curraldentense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3120904, "Curvelo", "curvelano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3121001, "Datas", "datense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3121100, "Delfim Moreira", "delfinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3121209, "Delfinópolis", "delfinopolitano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3121258, "Delta", "deltense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3121308, "Descoberto", "descobertense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3121407, "Desterro de Entre Rios", "desterrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3121506, "Desterro do Melo", "melense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3121605, "Diamantina", "diamantinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3121704, "Diogo de Vasconcelos", "vasconcelense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3121803, "Dionísio", "dionisiano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3121902, "Divinésia", "divinesiano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3122009, "Divino", "divinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3122108, "Divino das Laranjeiras", "divinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3122207, "Divinolândia de Minas", "divinolandense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3122306, "Divinópolis", "divinopolitano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3122355, "Divisa Alegre", "divisalegrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3122405, "Divisa Nova", "divisa-novense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3122454, "Divisópolis", "divisopolense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3122470, "Dom Bosco", "dom bosquense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3122504, "Dom Cavati", "dom-cavatiano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3122603, "Dom Joaquim", "dom-joaquinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3122702, "Dom Silvério", "dom-silveriense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3122801, "Dom Viçoso", "dom-viçosense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3122900, "Dona Eusébia", "euzebense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3123007, "Dores de Campos", "dorense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3123106, "Dores de Guanhães", "dorense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3123205, "Dores do Indaiá", "dorense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3123304, "Dores do Turvo", "dorense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3123403, "Doresópolis", "doresopolitano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3123502, "Douradoquara", "douradoquarense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3123528, "Durandé", "durandeense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3123601, "Elói Mendes", "elói-mendense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3123700, "Engenheiro Caldas", "engenheiro-caldense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3123809, "Engenheiro Navarro", "navarrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3123858, "Entre Folhas", "entrefolhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3123908, "Entre Rios de Minas", "entrerrianos", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3124005, "Ervália", "ervalense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3124104, "Esmeraldas", "esmeraldense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3124203, "Espera Feliz", "espera-felizense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3124302, "Espinosa", "espinosense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3124401, "Espírito Santo do Dourado", "douradense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3124500, "Estiva", "estivense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3124609, "Estrela Dalva", "estrela-dalvense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3124708, "Estrela do Indaiá", "estrelense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3124807, "Estrela do Sul", "estrela-sulense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3124906, "Eugenópolis", "eugenopolense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3125002, "Ewbank da Câmara", "ewbanquense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3125101, "Extrema", "extremense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3125200, "Fama", "famense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3125309, "Faria Lemos", "faria-lemense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3125408, "Felício dos Santos", "feliz-santense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3125606, "Felisburgo", "felisburguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3125705, "Felixlândia", "felixlandense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3125804, "Fernandes Tourinho", "fernandes-tourinhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3125903, "Ferros", "ferrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3125952, "Fervedouro", "fervedourense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3126000, "Florestal", "florestalense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3126109, "Formiga", "formiguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3126208, "Formoso", "formosense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3126307, "Fortaleza de Minas", "fortalezense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3126406, "Fortuna de Minas", "fortunense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3126505, "Francisco Badaró", "badarosense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3126604, "Francisco Dumont", "francisco-dumonsense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3126703, "Francisco Sá", "francisco-saense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3126752, "Franciscópolis", "franciscopolitano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3126802, "Frei Gaspar", "frei-gasparense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3126901, "Frei Inocêncio", "frei-inocenciano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3126950, "Frei Lagonegro", "frei lagonegrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3127008, "Fronteira", "fronteirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3127057, "Fronteira dos Vales", "fronteirista-dos-vales", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3127073, "Fruta de Leite", "fruta de leitense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3127107, "Frutal", "frutalense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3127206, "Funilândia", "funilandense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3127305, "Galiléia", "galileense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3127339, "Gameleiras", "gameleirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3127354, "Glaucilândia", "glaucilandense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3127370, "Goiabeira", "goiabeirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3127388, "Goianá", "goianaense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3127404, "Gonçalves", "gonçalvense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3127503, "Gonzaga", "gonzaguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3127602, "Gouveia", "gouveano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3127701, "Governador Valadares", "valadarense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3127800, "Grão Mogol", "grão-mogolense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3127909, "Grupiara", "grupiarense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3128006, "Guanhães", "guanhanense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3128105, "Guapé", "guapense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3128204, "Guaraciaba", "guaraciabense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3128253, "Guaraciama", "guaraciamense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3128303, "Guaranésia", "guaranesiano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3128402, "Guarani", "guaraniense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3128501, "Guarará", "guararense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3128600, "Guarda-Mor", "guarda-morense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3128709, "Guaxupé", "guaxupeano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3128808, "Guidoval", "guidovalense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3128907, "Guimarânia", "guimaranense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3129004, "Guiricema", "guiricemense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3129103, "Gurinhatã", "gurinhantense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3129202, "Heliodora", "heliodorense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3129301, "Iapu", "iapuense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3129400, "Ibertioga", "ibertiogano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3129509, "Ibiá", "ibiaense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3129608, "Ibiaí", "ibiaiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3129657, "Ibiracatu", "ibiracatuense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3129707, "Ibiraci", "ibiraciense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3129806, "Ibirité", "ibiritenense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3129905, "Ibitiúra de Minas", "ibitiurense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3130002, "Ibituruna", "ibiturunense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3130051, "Icaraí de Minas", "icaraiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3130101, "Igarapé", "igarapeense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3130200, "Igaratinga", "igaratinguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3130309, "Iguatama", "iguatamense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3130408, "Ijaci", "ijaciense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3130507, "Ilicínea", "ilicineaense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3130556, "Imbé de Minas", "imbeense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3130606, "Inconfidentes", "inconfidentino", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3130655, "Indaiabira", "indaiabirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3130705, "Indianópolis", "indianopolense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3130804, "Ingaí", "ingaiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3130903, "Inhapim", "inhapinhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3131000, "Inhaúma", "inhaumense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3131109, "Inimutaba", "inimutabano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3131158, "Ipaba", "ipabense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3131208, "Ipanema", "ipanemense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3131307, "Ipatinga", "ipatinguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3131406, "Ipiaçu", "ipiaçuense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3131505, "Ipuiúna", "ipuiunense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3131604, "Iraí de Minas", "iraiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3131703, "Itabira", "itabirano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3131802, "Itabirinha", "itabirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3131901, "Itabirito", "itabiritense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3132008, "Itacambira", "itacambirano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3132107, "Itacarambi", "itacarambiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3132206, "Itaguara", "itaguarense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3132305, "Itaipé", "itaipeense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3132404, "Itajubá", "itajubense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3132503, "Itamarandiba", "itamarandibano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3132602, "Itamarati de Minas", "tamaratiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3132701, "Itambacuri", "itambacuriense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3132800, "Itambé do Mato Dentro", "itambeense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3132909, "Itamogi", "itamogiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3133006, "Itamonte", "itamontense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3133105, "Itanhandu", "itanhanduense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3133204, "Itanhomi", "itanhomense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3133303, "Itaobim", "itaobinhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3133402, "Itapagipe", "itapagipense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3133501, "Itapecerica", "itapecericano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3133600, "Itapeva", "itapevense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3133709, "Itatiaiuçu", "itatiaiuçuense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3133758, "Itaú de Minas", "itauense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3133808, "Itaúna", "itaunense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3133907, "Itaverava", "itaveravense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3134004, "Itinga", "itinguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3134103, "Itueta", "ituetano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3134202, "Ituiutaba", "ituiutabano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3134301, "Itumirim", "itumirinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3134400, "Iturama", "ituramense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3134509, "Itutinga", "itutinguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3134608, "Jaboticatubas", "jaboticatubense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3134707, "Jacinto", "jacintense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3134806, "Jacuí", "jacuiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3134905, "Jacutinga", "jacutinguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3135001, "Jaguaraçu", "jaguaraçuense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3135050, "Jaíba", "jaibense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3135076, "Jampruca", "jampruquense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3135100, "Janaúba", "janaubense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3135209, "Januária", "januarense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3135308, "Japaraíba", "japaraíbano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3135357, "Japonvar", "japonvaense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3135407, "Jeceaba", "jeceabense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3135456, "Jenipapo de Minas", "jenipapense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3135506, "Jequeri", "jequeriense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3135605, "Jequitaí", "jequitaiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3135704, "Jequitibá", "jequitibaense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3135803, "Jequitinhonha", "jequitinhonhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3135902, "Jesuânia", "jesuanense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3136009, "Joaíma", "joaimense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3136108, "Joanésia", "joanense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3136207, "João Monlevade", "monlevadense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3136306, "João Pinheiro", "pinheirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3136405, "Joaquim Felício", "feliciano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3136504, "Jordânia", "jordainense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3136520, "José Gonçalves de Minas", "gonçalvense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3136553, "José Raydan", "josé raydanense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3136579, "Josenópolis", "josenopolense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3136652, "Juatuba", "juatubense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3136702, "Juiz de Fora", "juiz-forano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3136801, "Juramento", "juramentense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3136900, "Juruaia", "juruaiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3136959, "Juvenília", "juveniliense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3137007, "Ladainha", "ladainhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3137106, "Lagamar", "lagamaraense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3137205, "Lagoa da Prata", "lago-pratense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3137304, "Lagoa dos Patos", "lagoa-patense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3137403, "Lagoa Dourada", "lagoense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3137502, "Lagoa Formosa", "lagoense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3137536, "Lagoa Grande", "lagoa grandense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3137601, "Lagoa Santa", "lagoa-santense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3137700, "Lajinha", "lajinhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3137809, "Lambari", "lambariense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3137908, "Lamim", "laminense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3138005, "Laranjal", "laranjalense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3138104, "Lassance", "lassancense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3138203, "Lavras", "lavrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3138302, "Leandro Ferreira", "leandrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3138351, "Leme do Prado", "lemepradense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3138401, "Leopoldina", "leopoldinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3138500, "Liberdade", "libertense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3138609, "Lima Duarte", "limaduartino", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3138625, "Limeira do Oeste", "limeirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3138658, "Lontra", "lontrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3138674, "Luisburgo", "luisburguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3138682, "Luislândia", "luislandense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3138708, "Luminárias", "luminarense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3138807, "Luz", "luzense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3138906, "Machacalis", "machacalisense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3139003, "Machado", "machadense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3139102, "Madre de Deus de Minas", "madre-deusense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3139201, "Malacacheta", "malacachetense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3139250, "Mamonas", "mamonense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3139300, "Manga", "manguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3139409, "Manhuaçu", "manhuaçuense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3139508, "Manhumirim", "manhumiriense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3139607, "Mantena", "mantenense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3139805, "Mar de Espanha", "mar-de-espanhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3139706, "Maravilhas", "maravilhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3139904, "Maria da Fé", "mariense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3140001, "Mariana", "marianense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3140100, "Marilac", "marilaquense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3140159, "Mário Campos", "mario-campense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3140209, "Maripá de Minas", "maripaense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3140308, "Marliéria", "marlierense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3140407, "Marmelópolis", "marmelopolense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3140506, "Martinho Campos", "martinho-campense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3140530, "Martins Soares", "martinsoarense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3140555, "Mata Verde", "mataverdense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3140605, "Materlândia", "materlandiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3140704, "Mateus Leme", "mateus-lemense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3171501, "Mathias Lobato", "matiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3140803, "Matias Barbosa", "matiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3140852, "Matias Cardoso", "matiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3140902, "Matipó", "matipoense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3141009, "Mato Verde", "mato-verdense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3141108, "Matozinhos", "matozinhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3141207, "Matutina", "matutinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3141306, "Medeiros", "medeirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3141405, "Medina", "medinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3141504, "Mendes Pimentel", "pimentelense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3141603, "Mercês", "mercesano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3141702, "Mesquita", "mesquitense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3141801, "Minas Novas", "minas-novense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3141900, "Minduri", "mindurense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3142007, "Mirabela", "mirabelense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3142106, "Miradouro", "miradourense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3142205, "Miraí", "miraiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3142254, "Miravânia", "miravaniense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3142304, "Moeda", "moedense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3142403, "Moema", "moemense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3142502, "Monjolos", "monjolense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3142601, "Monsenhor Paulo", "paulense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3142700, "Montalvânia", "montalvanense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3142809, "Monte Alegre de Minas", "monte-alegrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3142908, "Monte Azul", "monte-azulense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3143005, "Monte Belo", "monte-belano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3143104, "Monte Carmelo", "carmelitano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3143153, "Monte Formoso", "monte formosense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3143203, "Monte Santo de Minas", "monte-santense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3143401, "Monte Sião", "monte-sionense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3143302, "Montes Claros", "montes-clarense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3143450, "Montezuma", "montesumense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3143500, "Morada Nova de Minas", "moradense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3143609, "Morro da Garça", "morrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3143708, "Morro do Pilar", "morrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3143807, "Munhoz", "munhozense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3143906, "Muriaé", "muriaense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3144003, "Mutum", "mutuense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3144102, "Muzambinho", "muzambinhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3144201, "Nacip Raydan", "nacipense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3144300, "Nanuque", "nanuquense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3144359, "Naque", "naquense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3144375, "Natalândia", "natalandense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3144409, "Natércia", "naterciano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3144508, "Nazareno", "nazarenense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3144607, "Nepomuceno", "nepomucenense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3144656, "Ninheira", "ninheirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3144672, "Nova Belém", "belenense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3144706, "Nova Era", "nova-erense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3144805, "Nova Lima", "nova-limense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3144904, "Nova Módica", "neomodicano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3145000, "Nova Ponte", "nova-pontense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3145059, "Nova Porteirinha", "novaporteirinhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3145109, "Nova Resende", "resendense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3145208, "Nova Serrana", "nova-serranense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3136603, "Nova União", "nova-uniense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3145307, "Novo Cruzeiro", "novo-cruzeirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3145356, "Novo Oriente de Minas", "novo orientense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3145372, "Novorizonte", "novorizontino", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3145406, "Olaria", "olariense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3145455, "Olhos-d'Água", "olhos-d'aguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3145505, "Olímpio Noronha", "olímpio-noroense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3145604, "Oliveira", "oliveirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3145703, "Oliveira Fortes", "oliveira-fortense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3145802, "Onça de Pitangui", "oncense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3145851, "Oratórios", "oratoriense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3145877, "Orizânia", "orizanense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3145901, "Ouro Branco", "ouro-branquense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3146008, "Ouro Fino", "ouro-finense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3146107, "Ouro Preto", "ouro-pretano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3146206, "Ouro Verde de Minas", "ouro-verdense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3146255, "Padre Carvalho", "padre carvaliense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3146305, "Padre Paraíso", "padre-paraisense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3146552, "Pai Pedro", "paipedrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3146404, "Paineiras", "paineirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3146503, "Pains", "painense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3146602, "Paiva", "paivense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3146701, "Palma", "palmense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3146750, "Palmópolis", "palmopolense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3146909, "Papagaios", "papagaiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3147105, "Pará de Minas", "paraense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3147006, "Paracatu", "paracatuense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3147204, "Paraguaçu", "paraguaçuense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3147303, "Paraisópolis", "paraisopolense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3147402, "Paraopeba", "paraopebense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3147600, "Passa Quatro", "passa-quatrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3147709, "Passa Tempo", "passa-tempense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3147808, "Passa-Vinte", "passa-vintense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3147501, "Passabém", "passabenense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3147907, "Passos", "passense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3147956, "Patis", "patiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3148004, "Patos de Minas", "patense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3148103, "Patrocínio", "patrocinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3148202, "Patrocínio do Muriaé", "patrocinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3148301, "Paula Cândido", "paula-candense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3148400, "Paulistas", "paulistano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3148509, "Pavão", "pavoense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3148608, "Peçanha", "peçanhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3148707, "Pedra Azul", "pedra-azulense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3148756, "Pedra Bonita", "pedrabonitense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3148806, "Pedra do Anta", "antense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3148905, "Pedra do Indaiá", "andaiaense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3149002, "Pedra Dourada", "douradense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3149101, "Pedralva", "pedralvense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3149150, "Pedras de Maria da Cruz", "pedrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3149200, "Pedrinópolis", "pedrinopolense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3149309, "Pedro Leopoldo", "pedro-leopoldense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3149408, "Pedro Teixeira", "pedro-teixeirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3149507, "Pequeri", "pequeriense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3149606, "Pequi", "pequiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3149705, "Perdigão", "perdiguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3149804, "Perdizes", "perdizense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3149903, "Perdões", "perdoense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3149952, "Periquito", "periquitense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3150000, "Pescador", "pescadorense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3150109, "Piau", "piauense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3150158, "Piedade de Caratinga", "piedade-caratinguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3150208, "Piedade de Ponte Nova", "piedadense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3150307, "Piedade do Rio Grande", "piedadense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3150406, "Piedade dos Gerais", "piedadense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3150505, "Pimenta", "pimentense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3150539, "Pingo-d'Água", "pingodaguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3150570, "Pintópolis", "pintopolense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3150604, "Piracema", "piracemense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3150703, "Pirajuba", "pirajubense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3150802, "Piranga", "piranguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3150901, "Piranguçu", "piranguçuense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3151008, "Piranguinho", "piranguinhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3151107, "Pirapetinga", "pirapetinguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3151206, "Pirapora", "piraporense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3151305, "Piraúba", "piraubano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3151404, "Pitangui", "pitanguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3151503, "Piumhi", "piuiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3151602, "Planura", "planurense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3151701, "Poço Fundo", "poço-fundense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3151800, "Poços de Caldas", "poços-caldense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3151909, "Pocrane", "pocranense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3152006, "Pompéu", "pompeano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3152105, "Ponte Nova", "ponte-novense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3152131, "Ponto Chique", "ponto chiquense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3152170, "Ponto dos Volantes", "ponto volantense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3152204, "Porteirinha", "porteirinhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3152303, "Porto Firme", "porto-firmense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3152402, "Poté", "poteense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3152501, "Pouso Alegre", "pouso-alegrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3152600, "Pouso Alto", "pouso-altense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3152709, "Prados", "pradense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3152808, "Prata", "pratense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3152907, "Pratápolis", "pratapolense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3153004, "Pratinha", "pratinhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3153103, "Presidente Bernardes", "bernardense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3153202, "Presidente Juscelino", "juscelinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3153301, "Presidente Kubitschek", "kubitschekano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3153400, "Presidente Olegário", "olegariense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3153608, "Prudente de Morais", "prudentino", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3153707, "Quartel Geral", "quartelense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3153806, "Queluzito", "queluzitano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3153905, "Raposos", "raposense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3154002, "Raul Soares", "raul-soarense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3154101, "Recreio", "recreiense ou recreense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3154150, "Reduto", "redutense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3154200, "Resende Costa", "resende-costense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3154309, "Resplendor", "resplendorense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3154408, "Ressaquinha", "ressaquinhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3154457, "Riachinho", "riachiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3154507, "Riacho dos Machados", "riachense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3154606, "Ribeirão das Neves", "nevense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3154705, "Ribeirão Vermelho", "ribeirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3154804, "Rio Acima", "rio-acimense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3154903, "Rio Casca", "rio-casquense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3155108, "Rio do Prado", "rio-pradense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3155009, "Rio Doce", "rio-docense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3155207, "Rio Espera", "rio-esperense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3155306, "Rio Manso", "rio-mansense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3155405, "Rio Novo", "rio-novense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3155504, "Rio Paranaíba", "rio-paraibano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3155603, "Rio Pardo de Minas", "rio-pardense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3155702, "Rio Piracicaba", "piracicabense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3155801, "Rio Pomba", "rio-pombense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3155900, "Rio Preto", "rio-pretense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3156007, "Rio Vermelho", "rio-vermelhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3156106, "Ritápolis", "ritapolitano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3156205, "Rochedo de Minas", "rochedense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3156304, "Rodeiro", "rodeirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3156403, "Romaria", "romariense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3156452, "Rosário da Limeira", "limeirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3156502, "Rubelita", "rubelitense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3156601, "Rubim", "rubinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3156700, "Sabará", "sabaraense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3156809, "Sabinópolis", "sabinopolense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3156908, "Sacramento", "sacramentense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3157005, "Salinas", "salinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3157104, "Salto da Divisa", "saltense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3157203, "Santa Bárbara", "santa-barbarense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3157252, "Santa Bárbara do Leste", "santa barbarense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3157278, "Santa Bárbara do Monte Verde", "barbarense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3157302, "Santa Bárbara do Tugúrio", "tugurense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3157336, "Santa Cruz de Minas", "santacruzense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3157377, "Santa Cruz de Salinas", "santacruzense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3157401, "Santa Cruz do Escalvado", "santa-cruzense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3157500, "Santa Efigênia de Minas", "santa-efigense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3157609, "Santa Fé de Minas", "santa-feense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3157658, "Santa Helena de Minas", "santaelenense de minas", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3157708, "Santa Juliana", "santa-julianense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3157807, "Santa Luzia", "luziense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3157906, "Santa Margarida", "santa-margaridense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3158003, "Santa Maria de Itabira", "santa-mariense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3158102, "Santa Maria do Salto", "santa-mariense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3158201, "Santa Maria do Suaçuí", "santa-mariense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3159209, "Santa Rita de Caldas", "santa-ritense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3159407, "Santa Rita de Ibitipoca", "ibitipoquense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3159308, "Santa Rita de Jacutinga", "santa-ritense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3159357, "Santa Rita de Minas", "santa-ritense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3159506, "Santa Rita do Itueto", "santa-ritense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3159605, "Santa Rita do Sapucaí", "santa-ritense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3159704, "Santa Rosa da Serra", "rosalense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3159803, "Santa Vitória", "santa-vitoriense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3158300, "Santana da Vargem", "vargense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3158409, "Santana de Cataguases", "santanense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3158508, "Santana de Pirapama", "pirapamenho", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3158607, "Santana do Deserto", "santanense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3158706, "Santana do Garambéu", "santanense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3158805, "Santana do Jacaré", "santanense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3158904, "Santana do Manhuaçu", "santanense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3158953, "Santana do Paraíso", "paraisense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3159001, "Santana do Riacho", "riachense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3159100, "Santana dos Montes", "santanense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3159902, "Santo Antônio do Amparo", "amparense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3160009, "Santo Antônio do Aventureiro", "aventureirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3160108, "Santo Antônio do Grama", "gramense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3160207, "Santo Antônio do Itambé", "itambeano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3160306, "Santo Antônio do Jacinto", "santo-antoniense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3160405, "Santo Antônio do Monte", "santo-antoniense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3160454, "Santo Antônio do Retiro", "retirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3160504, "Santo Antônio do Rio Abaixo", "santo-antoniense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3160603, "Santo Hipólito", "santo-hipolitense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3160702, "Santos Dumont", "sandumonense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3160801, "São Bento Abade", "são-bentista", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3160900, "São Brás do Suaçuí", "suaçuiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3160959, "São Domingos das Dores", "sandominguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3161007, "São Domingos do Prata", "pratense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3161056, "São Félix de Minas", "são felense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3161106, "São Francisco", "são-franciscano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3161205, "São Francisco de Paula", "francisco-paulense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3161304, "São Francisco de Sales", "são-francisco-salense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3161403, "São Francisco do Glória", "são-franciscano-do-glória", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3161502, "São Geraldo", "são-geraldense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3161601, "São Geraldo da Piedade", "são-geraldense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3161650, "São Geraldo do Baixio", "baixiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3161700, "São Gonçalo do Abaeté", "são-gonçalense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3161809, "São Gonçalo do Pará", "são-gonçalense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3161908, "São Gonçalo do Rio Abaixo", "são-gonçalense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3125507, "São Gonçalo do Rio Preto", "são-gonçalense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3162005, "São Gonçalo do Sapucaí", "são-gonçalense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3162104, "São Gotardo", "são-gotardense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3162203, "São João Batista do Glória", "gloriense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3162252, "São João da Lagoa", "lagoano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3162302, "São João da Mata", "são-joanense-da-mata", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3162401, "São João da Ponte", "pontense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3162450, "São João das Missões", "missionense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3162500, "São João del Rei", "são-joanense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3162559, "São João do Manhuaçu", "sanjoanense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3162575, "São João do Manteninha", "manteniense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3162609, "São João do Oriente", "são-joanense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3162658, "São João do Pacuí", "pacuíense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3162708, "São João do Paraíso", "paraisense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3162807, "São João Evangelista", "evangelistano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3162906, "São João Nepomuceno", "são-joanense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3162922, "São Joaquim de Bicas", "sanjoaquimbiquense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3162948, "São José da Barra", "são josé barrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3162955, "São José da Lapa", "lapense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3163003, "São José da Safira", "safirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3163102, "São José da Varginha", "varginense-de-são-josé", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3163201, "São José do Alegre", "alegrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3163300, "São José do Divino", "são-josé-divinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3163409, "São José do Goiabal", "goiabalense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3163508, "São José do Jacuri", "jacuriense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3163607, "São José do Mantimento", "mantimentense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3163706, "São Lourenço", "são-lourenciano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3163805, "São Miguel do Anta", "são-miguelense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3163904, "São Pedro da União", "são-pedrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3164100, "São Pedro do Suaçuí", "são-pedrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3164001, "São Pedro dos Ferros", "ferrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3164209, "São Romão", "são-romano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3164308, "São Roque de Minas", "são-roquense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3164407, "São Sebastião da Bela Vista", "bela-vistense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3164431, "São Sebastião da Vargem Alegre", "são sebastião vargem alegrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3164472, "São Sebastião do Anta", "antense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3164506, "São Sebastião do Maranhão", "maranhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3164605, "São Sebastião do Oeste", "sebastianense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3164704, "São Sebastião do Paraíso", "paraisense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3164803, "São Sebastião do Rio Preto", "são-sebastianense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3164902, "São Sebastião do Rio Verde", "rio-verdense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3165206, "São Thomé das Letras", "são-tomeense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3165008, "São Tiago", "são-tiaguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3165107, "São Tomás de Aquino", "aquinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3165305, "São Vicente de Minas", "vicenciano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3165404, "Sapucaí-Mirim", "sapucaiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3165503, "Sardoá", "sardoense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3165537, "Sarzedo", "sarzedense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3165560, "Sem-Peixe", "sempeixiano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3165578, "Senador Amaral", "amaralense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3165602, "Senador Cortes", "senador-cortense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3165701, "Senador Firmino", "firminense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3165800, "Senador José Bento", "senabentense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3165909, "Senador Modestino Gonçalves", "modestinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3166006, "Senhora de Oliveira", "oliveirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3166105, "Senhora do Porto", "portuense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3166204, "Senhora dos Remédios", "remediense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3166303, "Sericita", "sericitense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3166402, "Seritinga", "seritinguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3166501, "Serra Azul de Minas", "serra-azulense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3166600, "Serra da Saudade", "serrano-saudalense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3166808, "Serra do Salitre", "serralitrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3166709, "Serra dos Aimorés", "serrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3166907, "Serrania", "serraniense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3166956, "Serranópolis de Minas", "serranopolitano de minas", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3167004, "Serranos", "serranense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3167103, "Serro", "serrano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3167202, "Sete Lagoas", "sete-lagoano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3165552, "Setubinha", "setubinhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3167301, "Silveirânia", "silveiranense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3167400, "Silvianópolis", "silvianopolense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3167509, "Simão Pereira", "simonense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3167608, "Simonésia", "simonense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3167707, "Sobrália", "sobraliense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3167806, "Soledade de Minas", "soledadense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3167905, "Tabuleiro", "tabuleirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3168002, "Taiobeiras", "taiobeirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3168051, "Taparuba", "taparubense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3168101, "Tapira", "tapirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3168200, "Tapiraí", "tapiraiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3168309, "Taquaraçu de Minas", "taquaraçuense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3168408, "Tarumirim", "tarumirinhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3168507, "Teixeiras", "teixeirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3168606, "Teófilo Otoni", "teófilo-otonense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3168705, "Timóteo", "timotense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3168804, "Tiradentes", "tiradentino", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3168903, "Tiros", "tirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3169000, "Tocantins", "tocantinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3169059, "Tocos do Moji", "tocos-mogiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3169109, "Toledo", "toledense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3169208, "Tombos", "tomboense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3169307, "Três Corações", "tricordiano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3169356, "Três Marias", "trimariense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3169406, "Três Pontas", "três-pontano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3169505, "Tumiritinga", "tumiritinguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3169604, "Tupaciguara", "tupaciguarense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3169703, "Turmalina", "turmalinense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3169802, "Turvolândia", "turvolandense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3169901, "Ubá", "ubaense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3170008, "Ubaí", "ubaiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3170057, "Ubaporanga", "ubaporanguense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3170107, "Uberaba", "uberabense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3170206, "Uberlândia", "uberlandense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3170305, "Umburatiba", "umburatibense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3170404, "Unaí", "unaiense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3170438, "União de Minas", "uniense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3170479, "Uruana de Minas", "uruanense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3170503, "Urucânia", "urucaniense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3170529, "Urucuia", "urucuiano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3170578, "Vargem Alegre", "vargealegrense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3170602, "Vargem Bonita", "vargiano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3170651, "Vargem Grande do Rio Pardo", "vargengrandense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3170701, "Varginha", "varginhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3170750, "Varjão de Minas", "varjonense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3170800, "Várzea da Palma", "várzea-palmense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3170909, "Varzelândia", "varzelandense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3171006, "Vazante", "vazantino", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3171030, "Verdelândia", "verdelandense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3171071, "Veredinha", "veredinhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3171105, "Veríssimo", "verissimense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3171154, "Vermelho Novo", "vermelhense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3171204, "Vespasiano", "vespasianense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3171303, "Viçosa", "viçosense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3171402, "Vieiras", "vieirense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3171600, "Virgem da Lapa", "virgem-lapense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3171709, "Virgínia", "virginense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3171808, "Virginópolis", "virginopolitano", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3171907, "Virgolândia", "virgolandense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3172004, "Visconde do Rio Branco", "rio-branquense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3172103, "Volta Grande", "volta-grandense", 31);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3172202, "Wenceslau Braz", "wenceslauense", 31);