INSERT INTO municipalities(code, name, gentilic, state) VALUES (3200102, "Afonso Cláudio", "afonso-claudense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3200169, "Água Doce do Norte", "água-docense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3200136, "Águia Branca", "aguiabranquense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3200201, "Alegre", "alegrense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3200300, "Alfredo Chaves", "alfredense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3200359, "Alto Rio Novo", "alto-rio-novense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3200409, "Anchieta", "anchietense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3200508, "Apiacá", "apiacaense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3200607, "Aracruz", "aracruzense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3200706, "Atilio Vivacqua", "atilio-vivacquense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3200805, "Baixo Guandu", "guanduense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3200904, "Barra de São Francisco", "franciscano", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3201001, "Boa Esperança", "esperancense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3201100, "Bom Jesus do Norte", "bom-jesuense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3201159, "Brejetuba", "brejetubense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3201209, "Cachoeiro de Itapemirim", "cachoeirense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3201308, "Cariacica", "cariaciquense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3201407, "Castelo", "castelense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3201506, "Colatina", "colatinense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3201605, "Conceição da Barra", "barrense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3201704, "Conceição do Castelo", "conceiçãoense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3201803, "Divino de São Lourenço", "são-lourencense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3201902, "Domingos Martins", "martinense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3202009, "Dores do Rio Preto", "rio-pretense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3202108, "Ecoporanga", "ecoporanguense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3202207, "Fundão", "fundãoense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3202256, "Governador Lindenberg", "lindenberguense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3202306, "Guaçuí", "guaçuiense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3202405, "Guarapari", "guarapariense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3202454, "Ibatiba", "ibatibense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3202504, "Ibiraçu", "ibiraçuense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3202553, "Ibitirama", "ibitiranense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3202603, "Iconha", "iconhense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3202652, "Irupi", "irupiense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3202702, "Itaguaçu", "itaguaçuense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3202801, "Itapemirim", "itapemirinense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3202900, "Itarana", "itaranense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3203007, "Iúna", "iunense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3203056, "Jaguaré", "jaguarense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3203106, "Jerônimo Monteiro", "monteirense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3203130, "João Neiva", "joão-neivense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3203163, "Laranja da Terra", "laranjense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3203205, "Linhares", "linharense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3203304, "Mantenópolis", "mantenopolisense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3203320, "Marataízes", "marataizense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3203346, "Marechal Floriano", "florianense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3203353, "Marilândia", "marilandense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3203403, "Mimoso do Sul", "mimosense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3203502, "Montanha", "montanhense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3203601, "Mucurici", "mucuriciense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3203700, "Muniz Freire", "muniz-freirense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3203809, "Muqui", "muquiense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3203908, "Nova Venécia", "veneciano", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3204005, "Pancas", "panquense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3204054, "Pedro Canário", "canariense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3204104, "Pinheiros", "pinheirense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3204203, "Piúma", "piumense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3204252, "Ponto Belo", "pontobelense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3204302, "Presidente Kennedy", "kennediense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3204351, "Rio Bananal", "ribanense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3204401, "Rio Novo do Sul", "novense-do-sul", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3204500, "Santa Leopoldina", "leopoldinense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3204559, "Santa Maria de Jetibá", "santa-mariense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3204609, "Santa Teresa", "teresense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3204658, "São Domingos do Norte", "dominguense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3204708, "São Gabriel da Palha", "gabrielense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3204807, "São José do Calçado", "calçadense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3204906, "São Mateus", "mateense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3204955, "São Roque do Canaã", "são-roquense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3205002, "Serra", "serrano", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3205010, "Sooretama", "sooretamense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3205036, "Vargem Alta", "vargem-altense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3205069, "Venda Nova do Imigrante", "venda-novense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3205101, "Viana", "vianense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3205150, "Vila Pavão", "pavoense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3205176, "Vila Valério", "vila-valense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3205200, "Vila Velha", "vila-velhense", 32);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3205309, "Vitória", "capixaba", 32);