INSERT INTO municipalities(code, name, gentilic, state) VALUES (3300100, "Angra dos Reis", "angrense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3300159, "Aperibé", "aperibeense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3300209, "Araruama", "araruamense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3300225, "Areal", "arealense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3300233, "Armação dos Búzios", "buziano", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3300258, "Arraial do Cabo", "cabista", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3300308, "Barra do Piraí", "barrense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3300407, "Barra Mansa", "barra-mansense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3300456, "Belford Roxo", "belford-roxense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3300506, "Bom Jardim", "bom-jardinense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3300605, "Bom Jesus do Itabapoana", "bom-jesuense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3300704, "Cabo Frio", "cabo-friense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3300803, "Cachoeiras de Macacu", "cachoeirense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3300902, "Cambuci", "cambuciense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3301009, "Campos dos Goytacazes", "campista", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3301108, "Cantagalo", "cantagalense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3300936, "Carapebus", "carapebuense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3301157, "Cardoso Moreira", "cardosense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3301207, "Carmo", "carmense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3301306, "Casimiro de Abreu", "casimirense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3300951, "Comendador Levy Gasparian", "gaspariense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3301405, "Conceição de Macabu", "macabuense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3301504, "Cordeiro", "cordeirense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3301603, "Duas Barras", "bibarrense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3301702, "Duque de Caxias", "caxiense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3301801, "Engenheiro Paulo de Frontin", "fronteense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3301850, "Guapimirim", "guapimiriense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3301876, "Iguaba Grande", "iguabense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3301900, "Itaboraí", "itaboraiense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3302007, "Itaguaí", "itaguaiense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3302056, "Italva", "italvense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3302106, "Itaocara", "itaocarense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3302205, "Itaperuna", "itaperunense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3302254, "Itatiaia", "itatiaiense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3302270, "Japeri", "japeriense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3302304, "Laje do Muriaé", "lajense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3302403, "Macaé", "macaense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3302452, "Macuco", "macuquense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3302502, "Magé", "mageense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3302601, "Mangaratiba", "mangaratibano", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3302700, "Maricá", "maricaense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3302809, "Mendes", "mendense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3302858, "Mesquita", "mesquitnese", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3302908, "Miguel Pereira", "miguelense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3303005, "Miracema", "miracemense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3303104, "Natividade", "natividadense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3303203, "Nilópolis", "nilopolitano", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3303302, "Niterói", "niteroiense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3303401, "Nova Friburgo", "friburguense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3303500, "Nova Iguaçu", "iguaçuano", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3303609, "Paracambi", "paracambiense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3303708, "Paraíba do Sul", "sul-paraibano", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3303807, "Paraty", "paratiense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3303856, "Paty do Alferes", "patiense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3303906, "Petrópolis", "petropolitano", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3303955, "Pinheiral", "pinheiralense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3304003, "Piraí", "piraiense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3304102, "Porciúncula", "porciunculense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3304110, "Porto Real", "porto realense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3304128, "Quatis", "quatiense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3304144, "Queimados", "queimadense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3304151, "Quissamã", "quissamaense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3304201, "Resende", "resendense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3304300, "Rio Bonito", "rio-bonitense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3304409, "Rio Claro", "rio-clarense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3304508, "Rio das Flores", "rio-florense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3304524, "Rio das Ostras", "rio ostrense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3304557, "Rio de Janeiro", "carioca", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3304607, "Santa Maria Madalena", "madalenense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3304706, "Santo Antônio de Pádua", "paduano", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3304805, "São Fidélis", "fidelense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3304755, "São Francisco de Itabapoana", "são franciscano", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3304904, "São Gonçalo", "gonçalense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3305000, "São João da Barra", "são-joanense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3305109, "São João de Meriti", "meritiense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3305133, "São José de Ubá", "ubaense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3305158, "São José do Vale do Rio Preto", "rio-pretano", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3305208, "São Pedro da Aldeia", "aldeiense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3305307, "São Sebastião do Alto", "altense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3305406, "Sapucaia", "sapucaiense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3305505, "Saquarema", "saquaremense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3305554, "Seropédica", "seropediquense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3305604, "Silva Jardim", "silva-jardinense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3305703, "Sumidouro", "sumidourense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3305752, "Tanguá", "tanguaense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3305802, "Teresópolis", "teresopolitano", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3305901, "Trajano de Moraes", "trajanense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3306008, "Três Rios", "trirriense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3306107, "Valença", "valenciano", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3306156, "Varre-Sai", "varresaiense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3306206, "Vassouras", "vassourense", 33);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (3306305, "Volta Redonda", "volta-redondense", 33);