INSERT INTO municipalities(code, name, gentilic, state) VALUES (4300034, "Aceguá", "aceguaense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4300059, "Água Santa", "água-santense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4300109, "Agudo", "agudense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4300208, "Ajuricaba", "ajuricabense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4300307, "Alecrim", "alecrinense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4300406, "Alegrete", "alegretense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4300455, "Alegria", "alegriense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4300471, "Almirante Tamandaré do Sul", "tamandarense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4300505, "Alpestre", "alpestrense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4300554, "Alto Alegre", "alto-alegrense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4300570, "Alto Feliz", "alto-felizense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4300604, "Alvorada", "alvoradense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4300638, "Amaral Ferrador", "amaralense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4300646, "Ametista do Sul", "ametistense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4300661, "André da Rocha", "andré-rochense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4300703, "Anta Gorda", "anta-gordense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4300802, "Antônio Prado", "pradense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4300851, "Arambaré", "arambarense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4300877, "Araricá", "arariquense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4300901, "Aratiba", "aratibense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4301008, "Arroio do Meio", "arroio-meense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4301073, "Arroio do Padre", "arroio padrense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4301057, "Arroio do Sal", "arroio-salense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4301206, "Arroio do Tigre", "tigrense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4301107, "Arroio dos Ratos", "ratense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4301305, "Arroio Grande", "arroio-grandense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4301404, "Arvorezinha", "arvorezinhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4301503, "Augusto Pestana", "augusto-pestanense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4301552, "Áurea", "aurense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4301602, "Bagé", "bageense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4301636, "Balneário Pinhal", "pinhalense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4301651, "Barão", "baronense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4301701, "Barão de Cotegipe", "cotegipense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4301750, "Barão do Triunfo", "baronense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4301859, "Barra do Guarita", "barra-guaritense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4301875, "Barra do Quaraí", "barrense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4301909, "Barra do Ribeiro", "barrense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4301925, "Barra do Rio Azul", "barra-azulense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4301958, "Barra Funda", "barra-fundense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4301800, "Barracão", "barraconense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4302006, "Barros Cassal", "barros-cassalense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4302055, "Benjamin Constant do Sul", "benjaminense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4302105, "Bento Gonçalves", "bento-gonçalvense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4302154, "Boa Vista das Missões", "boa-vistense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4302204, "Boa Vista do Buricá", "boa-vistense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4302220, "Boa Vista do Cadeado", "cadeadense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4302238, "Boa Vista do Incra", "boa vistense do incra", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4302253, "Boa Vista do Sul", "boavistense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4302303, "Bom Jesus", "bom-jesuense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4302352, "Bom Princípio", "bom-principiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4302378, "Bom Progresso", "bom-progressense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4302402, "Bom Retiro do Sul", "bom-retirense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4302451, "Boqueirão do Leão", "léo-boqueirense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4302501, "Bossoroca", "bossoroquense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4302584, "Bozano", "bozanense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4302600, "Braga", "braguense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4302659, "Brochier", "brochiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4302709, "Butiá", "butiaense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4302808, "Caçapava do Sul", "caçapavano", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4302907, "Cacequi", "cacequiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4303004, "Cachoeira do Sul", "cachoeirense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4303103, "Cachoeirinha", "cachoeirinhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4303202, "Cacique Doble", "caciquense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4303301, "Caibaté", "caibateense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4303400, "Caiçara", "caiçarense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4303509, "Camaquã", "camaquense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4303558, "Camargo", "camarguense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4303608, "Cambará do Sul", "cambaraense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4303673, "Campestre da Serra", "campestrense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4303707, "Campina das Missões", "campinense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4303806, "Campinas do Sul", "campinense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4303905, "Campo Bom", "campo-bonense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4304002, "Campo Novo", "campo-novense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4304101, "Campos Borges", "campos-borgense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4304200, "Candelária", "candelariense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4304309, "Cândido Godói", "godoiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4304358, "Candiota", "candiotense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4304408, "Canela", "canelense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4304507, "Canguçu", "canguçuense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4304606, "Canoas", "canoense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4304614, "Canudos do Vale", "canudense do vale", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4304622, "Capão Bonito do Sul", "capão bonitense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4304630, "Capão da Canoa", "caponense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4304655, "Capão do Cipó", "cipoense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4304663, "Capão do Leão", "leonense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4304689, "Capela de Santana", "capelense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4304697, "Capitão", "capitanense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4304671, "Capivari do Sul", "capivariense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4304713, "Caraá", "caraense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4304705, "Carazinho", "carazinhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4304804, "Carlos Barbosa", "barbosense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4304853, "Carlos Gomes", "carlos-gomense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4304903, "Casca", "casquense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4304952, "Caseiros", "caseirense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305009, "Catuípe", "catuipano", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305108, "Caxias do Sul", "caxiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305116, "Centenário", "centenariense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305124, "Cerrito", "cerritense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305132, "Cerro Branco", "cerro-branquense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305157, "Cerro Grande", "cerro-grandense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305173, "Cerro Grande do Sul", "sul-cerro-grandense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305207, "Cerro Largo", "cerro-larguense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305306, "Chapada", "chapadense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305355, "Charqueadas", "charqueadense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305371, "Charrua", "charruense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305405, "Chiapetta", "chiapetense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305439, "Chuí", "chuiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305447, "Chuvisca", "chuvisquense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305454, "Cidreira", "cidreirense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305504, "Ciríaco", "ciriaquense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305587, "Colinas", "colinense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305603, "Colorado", "coloradense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305702, "Condor", "condorense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305801, "Constantina", "constantinense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305835, "Coqueiro Baixo", "coqueirense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305850, "Coqueiros do Sul", "coqueirense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305871, "Coronel Barros", "coronel-barrense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305900, "Coronel Bicaco", "bicaquense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305934, "Coronel Pilar", "coronel pilarense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305959, "Cotiporã", "cotiporanense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4305975, "Coxilha", "coxilhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4306007, "Crissiumal", "crissiumalense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4306056, "Cristal", "cristalense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4306072, "Cristal do Sul", "cristalense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4306106, "Cruz Alta", "cruzaltense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4306130, "Cruzaltense", "cruzaltino", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4306205, "Cruzeiro do Sul", "cruzeirense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4306304, "David Canabarro", "canabarrense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4306320, "Derrubadas", "derrubadense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4306353, "Dezesseis de Novembro", "dezesseis-novembrense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4306379, "Dilermando de Aguiar", "dilermandense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4306403, "Dois Irmãos", "dois-irmãosense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4306429, "Dois Irmãos das Missões", "dois-irmãozense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4306452, "Dois Lajeados", "dois-lajeense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4306502, "Dom Feliciano", "felicianense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4306601, "Dom Pedrito", "pedritense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4306551, "Dom Pedro de Alcântara", "dom-pedro-alcantarense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4306700, "Dona Francisca", "francisquense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4306734, "Doutor Maurício Cardoso", "mauriciense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4306759, "Doutor Ricardo", "ricardense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4306767, "Eldorado do Sul", "eldoradense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4306809, "Encantado", "encantadense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4306908, "Encruzilhada do Sul", "encruzilhadense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4306924, "Engenho Velho", "engenho-velhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4306957, "Entre Rios do Sul", "entre-rio-sulense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4306932, "Entre-Ijuís", "entre-ijuiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4306973, "Erebango", "erebanguense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4307005, "Erechim", "erechinense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4307054, "Ernestina", "ernestinense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4307203, "Erval Grande", "erval-grandense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4307302, "Erval Seco", "erval-sequense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4307401, "Esmeralda", "esmeraldense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4307450, "Esperança do Sul", "esperançulense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4307500, "Espumoso", "espumosense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4307559, "Estação", "estacionense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4307609, "Estância Velha", "estanciense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4307708, "Esteio", "esteiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4307807, "Estrela", "estrelense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4307815, "Estrela Velha", "estrelavelhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4307831, "Eugênio de Castro", "eugenio-castrense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4307864, "Fagundes Varela", "fagundense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4307906, "Farroupilha", "farroupilhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4308003, "Faxinal do Soturno", "soturnense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4308052, "Faxinalzinho", "faxinalzinhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4308078, "Fazenda Vilanova", "vilanovense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4308102, "Feliz", "felizense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4308201, "Flores da Cunha", "florense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4308250, "Floriano Peixoto", "florianense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4308300, "Fontoura Xavier", "fontourense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4308409, "Formigueiro", "formigueirense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4308433, "Forquetinha", "forquetinhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4308458, "Fortaleza dos Valos", "fortalezense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4308508, "Frederico Westphalen", "westphalense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4308607, "Garibaldi", "garibaldense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4308656, "Garruchos", "garruchense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4308706, "Gaurama", "gauramense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4308805, "General Câmara", "camaraense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4308854, "Gentil", "gentilense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4308904, "Getúlio Vargas", "getuliense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4309001, "Giruá", "giruaense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4309050, "Glorinha", "glorinhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4309100, "Gramado", "gramadense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4309126, "Gramado dos Loureiros", "loureirense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4309159, "Gramado Xavier", "gramado-xavierense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4309209, "Gravataí", "gravataiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4309258, "Guabiju", "guabijuense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4309308, "Guaíba", "guaibense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4309407, "Guaporé", "guaporense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4309506, "Guarani das Missões", "guaraniense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4309555, "Harmonia", "harmoniense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4307104, "Herval", "hervalense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4309571, "Herveiras", "herveirense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4309605, "Horizontina", "horizontinense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4309654, "Hulha Negra", "hulha-negrense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4309704, "Humaitá", "humaitaense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4309753, "Ibarama", "ibaramense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4309803, "Ibiaçá", "ibiaçaense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4309902, "Ibiraiaras", "ibiraiarense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4309951, "Ibirapuitã", "ibirapuitanense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4310009, "Ibirubá", "ibirubense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4310108, "Igrejinha", "igrejinhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4310207, "Ijuí", "ijuiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4310306, "Ilópolis", "ilopolitano", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4310330, "Imbé", "Imbeense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4310363, "Imigrante", "imigrantense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4310405, "Independência", "independenciense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4310413, "Inhacorá", "inhacorense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4310439, "Ipê", "ipeense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4310462, "Ipiranga do Sul", "ipiranguense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4310504, "Iraí", "iraiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4310538, "Itaara", "itaarense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4310553, "Itacurubi", "itacurubiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4310579, "Itapuca", "itapuquense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4310603, "Itaqui", "itaquiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4310652, "Itati", "itatiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4310702, "Itatiba do Sul", "itatibense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4310751, "Ivorá", "ivorense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4310801, "Ivoti", "ivotiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4310850, "Jaboticaba", "jaboticabense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4310876, "Jacuizinho", "jacuizinhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4310900, "Jacutinga", "jacutinguense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4311007, "Jaguarão", "jaguarense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4311106, "Jaguari", "jaguariense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4311122, "Jaquirana", "jaquiranense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4311130, "Jari", "jariense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4311155, "Jóia", "joiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4311205, "Júlio de Castilhos", "castilhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4311239, "Lagoa Bonita do Sul", "lagobonitense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4311270, "Lagoa dos Três Cantos", "três-cantense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4311304, "Lagoa Vermelha", "lagoense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4311254, "Lagoão", "lagoense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4311403, "Lajeado", "lajeadense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4311429, "Lajeado do Bugre", "lajeado-bugrense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4311502, "Lavras do Sul", "lavrense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4311601, "Liberato Salzano", "salzanense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4311627, "Lindolfo Collor", "lindolfo-collorense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4311643, "Linha Nova", "linha-novense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4311718, "Maçambará", "maçambarense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4311700, "Machadinho", "machadinhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4311734, "Mampituba", "mampitubense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4311759, "Manoel Viana", "vianense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4311775, "Maquiné", "maquinense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4311791, "Maratá", "marataense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4311809, "Marau", "marauense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4311908, "Marcelino Ramos", "marcelinense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4311981, "Mariana Pimentel", "marianense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312005, "Mariano Moro", "marianense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312054, "Marques de Souza", "marquesouzense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312104, "Mata", "matense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312138, "Mato Castelhano", "mato-castelhanense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312153, "Mato Leitão", "mato-leitoense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312179, "Mato Queimado", "matoqueimadense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312203, "Maximiliano de Almeida", "almeidense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312252, "Minas do Leão", "leonense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312302, "Miraguaí", "miraguaiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312351, "Montauri", "montauriense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312377, "Monte Alegre dos Campos", "montealegrense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312385, "Monte Belo do Sul", "monte-belense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312401, "Montenegro", "montenegrino", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312427, "Mormaço", "mormacense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312443, "Morrinhos do Sul", "morrinhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312450, "Morro Redondo", "morro-redondense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312476, "Morro Reuter", "morroreutense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312500, "Mostardas", "mostardense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312609, "Muçum", "muçuense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312617, "Muitos Capões", "caponense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312625, "Muliterno", "muliternense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312658, "Não-Me-Toque", "não-me-toquense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312674, "Nicolau Vergueiro", "nicolau-vergueirense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312708, "Nonoai", "nonoaiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312757, "Nova Alvorada", "nova-alvoradense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312807, "Nova Araçá", "araçaense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312906, "Nova Bassano", "bassanense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4312955, "Nova Boa Vista", "boa-vistense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4313003, "Nova Bréscia", "bresciense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4313011, "Nova Candelária", "nova-candelariense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4313037, "Nova Esperança do Sul", "nova-esperancense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4313060, "Nova Hartz", "nova-hartense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4313086, "Nova Pádua", "paduense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4313102, "Nova Palma", "nova-palmense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4313201, "Nova Petrópolis", "nova-petropolitano", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4313300, "Nova Prata", "nova-pratense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4313334, "Nova Ramada", "morador de nova rama", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4313359, "Nova Roma do Sul", "nova-romense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4313375, "Nova Santa Rita", "nova-santaritense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4313490, "Novo Barreiro", "novo-barreirense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4313391, "Novo Cabrais", "cabraisense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4313409, "Novo Hamburgo", "novo-hamburguense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4313425, "Novo Machado", "novo-machadense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4313441, "Novo Tiradentes", "tiradentense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4313466, "Novo Xingu", "xinguense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4313508, "Osório", "osoriense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4313607, "Paim Filho", "paim-filhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4313656, "Palmares do Sul", "palmarense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4313706, "Palmeira das Missões", "palmeirense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4313805, "Palmitinho", "palmitense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4313904, "Panambi", "panambiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4313953, "Pantano Grande", "pantanense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314001, "Paraí", "paraiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314027, "Paraíso do Sul", "paraisense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314035, "Pareci Novo", "pareciense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314050, "Parobé", "parobeense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314068, "Passa Sete", "passasetense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314076, "Passo do Sobrado", "passo-sobradense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314100, "Passo Fundo", "passo-fundense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314134, "Paulo Bento", "paulobentense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314159, "Paverama", "paveramense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314175, "Pedras Altas", "pedras altense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314209, "Pedro Osório", "pedro-osoriense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314308, "Pejuçara", "pejuçarense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314407, "Pelotas", "pelotense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314423, "Picada Café", "picadense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314456, "Pinhal", "pinhalense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314464, "Pinhal da Serra", "pinhalense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314472, "Pinhal Grande", "pinhal-grandense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314498, "Pinheirinho do Vale", "pinheirinhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314506, "Pinheiro Machado", "pinheirense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314548, "Pinto Bandeira", "pinto bandeirense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314555, "Pirapó", "pirapoense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314605, "Piratini", "piratinense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314704, "Planalto", "planaltense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314753, "Poço das Antas", "poçandense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314779, "Pontão", "pontanense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314787, "Ponte Preta", "ponte-pretense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314803, "Portão", "portanense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4314902, "Porto Alegre", "porto-alegrense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4315008, "Porto Lucena", "porto-lucenense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4315057, "Porto Mauá", "porto-mauense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4315073, "Porto Vera Cruz", "porto-vera-cruzense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4315107, "Porto Xavier", "porto-xavierense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4315131, "Pouso Novo", "pouso-novense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4315149, "Presidente Lucena", "lucinense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4315156, "Progresso", "progressense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4315172, "Protásio Alves", "protásio-alvense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4315206, "Putinga", "putinguense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4315305, "Quaraí", "quaraiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4315313, "Quatro Irmãos", "quatroirmanense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4315321, "Quevedos", "quevedense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4315354, "Quinze de Novembro", "quinze-novembrense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4315404, "Redentora", "redentorense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4315453, "Relvado", "relvadense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4315503, "Restinga Seca", "restinguense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4315552, "Rio dos Índios", "riodinhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4315602, "Rio Grande", "rio-grandino", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4315701, "Rio Pardo", "rio-pardense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4315750, "Riozinho", "riozinhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4315800, "Roca Sales", "roca-salense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4315909, "Rodeio Bonito", "rodeiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4315958, "Rolador", "roladorense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4316006, "Rolante", "rolantense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4316105, "Ronda Alta", "ronda-altense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4316204, "Rondinha", "rondinhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4316303, "Roque Gonzales", "roque-gonzalense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4316402, "Rosário do Sul", "rosariense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4316428, "Sagrada Família", "sagradense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4316436, "Saldanha Marinho", "saldanhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4316451, "Salto do Jacuí", "salto-jacuiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4316477, "Salvador das Missões", "salvadorense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4316501, "Salvador do Sul", "salvadorense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4316600, "Sananduva", "sananduvense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4317103, "Sant'Ana do Livramento", "santanense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4316709, "Santa Bárbara do Sul", "santa-barbarense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4316733, "Santa Cecília do Sul", "ceciliense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4316758, "Santa Clara do Sul", "santa-clarense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4316808, "Santa Cruz do Sul", "santa-cruzense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4316972, "Santa Margarida do Sul", "margaridense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4316907, "Santa Maria", "santa-mariense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4316956, "Santa Maria do Herval", "hervalense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4317202, "Santa Rosa", "santa-rosense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4317251, "Santa Tereza", "santa-teresense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4317301, "Santa Vitória do Palmar", "vitoriense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4317004, "Santana da Boa Vista", "santanense-da-boa-vista", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4317400, "Santiago", "santiaguense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4317509, "Santo Ângelo", "santo-angelense ou angelopolitano", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4317608, "Santo Antônio da Patrulha", "patrulhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4317707, "Santo Antônio das Missões", "santo-antoniense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4317558, "Santo Antônio do Palma", "palmense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4317756, "Santo Antônio do Planalto", "santo-antoniense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4317806, "Santo Augusto", "santo-augustense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4317905, "Santo Cristo", "santo-cristense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4317954, "Santo Expedito do Sul", "expeditense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4318002, "São Borja", "são borjense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4318051, "São Domingos do Sul", "são-dominguense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4318101, "São Francisco de Assis", "assisense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4318200, "São Francisco de Paula", "serrano", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4318309, "São Gabriel", "gabrielense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4318408, "São Jerônimo", "jeronimense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4318424, "São João da Urtiga", "urtiguense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4318432, "São João do Polêsine", "polesinense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4318440, "São Jorge", "são-jorgense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4318457, "São José das Missões", "são-josezense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4318465, "São José do Herval", "hervalense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4318481, "São José do Hortêncio", "hortenciense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4318499, "São José do Inhacorá", "inhacoraense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4318507, "São José do Norte", "nortense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4318606, "São José do Ouro", "ourense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4318614, "São José do Sul", "são josense do sul", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4318622, "São José dos Ausentes", "ausentino", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4318705, "São Leopoldo", "leopoldense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4318804, "São Lourenço do Sul", "lourenciano", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4318903, "São Luiz Gonzaga", "são-luizense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4319000, "São Marcos", "são-marquense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4319109, "São Martinho", "são-martinhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4319125, "São Martinho da Serra", "martinhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4319158, "São Miguel das Missões", "miguelino", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4319208, "São Nicolau", "são-nicolauense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4319307, "São Paulo das Missões", "paulista-das-missões", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4319356, "São Pedro da Serra", "são-pedrense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4319364, "São Pedro das Missões", "são pedrense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4319372, "São Pedro do Butiá", "são-butiaiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4319406, "São Pedro do Sul", "são-pedrense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4319505, "São Sebastião do Caí", "caiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4319604, "São Sepé", "sepense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4319703, "São Valentim", "valentinense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4319711, "São Valentim do Sul", "são-valentinense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4319737, "São Valério do Sul", "são-valerense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4319752, "São Vendelino", "são-vendelinense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4319802, "São Vicente do Sul", "vicentino", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4319901, "Sapiranga", "sapiranguense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4320008, "Sapucaia do Sul", "sapucaiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4320107, "Sarandi", "sarandiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4320206, "Seberi", "seberiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4320230, "Sede Nova", "sede-novense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4320263, "Segredo", "segredense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4320305, "Selbach", "selbaquense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4320321, "Senador Salgado Filho", "salgadofilhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4320354, "Sentinela do Sul", "sentinelense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4320404, "Serafina Corrêa", "serafinense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4320453, "Sério", "seriense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4320503, "Sertão", "sertanense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4320552, "Sertão Santana", "sertanense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4320578, "Sete de Setembro", "setembrense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4320602, "Severiano de Almeida", "severianense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4320651, "Silveira Martins", "sillveirense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4320677, "Sinimbu", "sinimbuense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4320701, "Sobradinho", "sobradinhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4320800, "Soledade", "soledadense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4320859, "Tabaí", "tabaiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4320909, "Tapejara", "tapejarense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4321006, "Tapera", "taperense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4321105, "Tapes", "tapense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4321204, "Taquara", "taquarense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4321303, "Taquari", "taquariense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4321329, "Taquaruçu do Sul", "taquaraçusense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4321352, "Tavares", "tavarense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4321402, "Tenente Portela", "portelense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4321436, "Terra de Areia", "terrareense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4321451, "Teutônia", "teutoniense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4321469, "Tio Hugo", "tio-huguense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4321477, "Tiradentes do Sul", "tiradentense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4321493, "Toropi", "toropiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4321501, "Torres", "torrense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4321600, "Tramandaí", "tramandaiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4321626, "Travesseiro", "travesseirense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4321634, "Três Arroios", "três-arroiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4321667, "Três Cachoeiras", "três cachoeirense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4321709, "Três Coroas", "três-coroense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4321808, "Três de Maio", "três-maiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4321832, "Três Forquilhas", "forquilhense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4321857, "Três Palmeiras", "três-palmeirense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4321907, "Três Passos", "três-passense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4321956, "Trindade do Sul", "trindadense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4322004, "Triunfo", "triunfense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4322103, "Tucunduva", "tucunduvense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4322152, "Tunas", "tunense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4322186, "Tupanci do Sul", "tupancisense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4322202, "Tupanciretã", "tupanciretanense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4322251, "Tupandi", "tupandiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4322301, "Tuparendi", "tuparendiense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4322327, "T'uruçu", "turuçuense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4322343, "Ubiretama", "ubiretamense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4322350, "União da Serra", "união-serrense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4322376, "Unistalda", "unistaldense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4322400, "Uruguaiana", "uruguaianense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4322509, "Vacaria", "vacariense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4322533, "Vale do Sol", "vale-solense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4322541, "Vale Real", "vale-realense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4322525, "Vale Verde", "valeverdense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4322558, "Vanini", "vaninense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4322608, "Venâncio Aires", "venâncio-airense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4322707, "Vera Cruz", "vera-cruzense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4322806, "Veranópolis", "veranense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4322855, "Vespasiano Correa", "vespasianense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4322905, "Viadutos", "viadutense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4323002, "Viamão", "viamense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4323101, "Vicente Dutra", "dutrense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4323200, "Victor Graeff", "victorense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4323309, "Vila Flores", "vila-florense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4323358, "Vila Lângaro", "vila-langarense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4323408, "Vila Maria", "vila-mariense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4323457, "Vila Nova do Sul", "vila-novense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4323507, "Vista Alegre", "vista-alegrense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4323606, "Vista Alegre do Prata", "vista-alegrense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4323705, "Vista Gaúcha", "vista-gauchense", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4323754, "Vitória das Missões", "vitoriano", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4323770, "Westfália", "westfaliano", 43);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (4323804, "Xangri-lá", "xangri-laense", 43);