INSERT INTO municipalities(code, name, gentilic, state) VALUES (5200050, "Abadia de Goiás", "abadiense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5200100, "Abadiânia", "abadiense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5200134, "Acreúna", "acreunense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5200159, "Adelândia", "adelandense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5200175, "Água Fria de Goiás", "água-friense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5200209, "Água Limpa", "água-limpense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5200258, "Águas Lindas de Goiás", "águas lindense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5200308, "Alexânia", "alexaniense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5200506, "Aloândia", "aloandense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5200555, "Alto Horizonte", "alto horizontino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5200605, "Alto Paraíso de Goiás", "alto-paraisense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5200803, "Alvorada do Norte", "alvoradense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5200829, "Amaralina", "amaralinense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5200852, "Americano do Brasil", "americanense-do-Brasil", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5200902, "Amorinópolis", "amorinopolense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5201108, "Anápolis", "anapolino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5201207, "Anhanguera", "anhanguerino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5201306, "Anicuns", "anicuense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5201405, "Aparecida de Goiânia", "aparecidense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5201454, "Aparecida do Rio Doce", "riodocense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5201504, "Aporé", "aporeano", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5201603, "Araçu", "araçuense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5201702, "Aragarças", "aragarcense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5201801, "Aragoiânia", "aragoianense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5202155, "Araguapaz", "araguapaense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5202353, "Arenópolis", "arenopolino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5202502, "Aruanã", "aruanense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5202601, "Aurilândia", "aurilandense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5202809, "Avelinópolis", "avelinopense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5203104, "Baliza", "balizense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5203203, "Barro Alto", "barro-altense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5203302, "Bela Vista de Goiás", "bela-vistense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5203401, "Bom Jardim de Goiás", "bom-jardinense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5203500, "Bom Jesus de Goiás", "bom-jesuense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5203559, "Bonfinópolis", "bonfinopolino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5203575, "Bonópolis", "bonopolino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5203609, "Brazabrantes", "brazabrantino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5203807, "Britânia", "britaniense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5203906, "Buriti Alegre", "buriti-alegrense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5203939, "Buriti de Goiás", "buritiense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5203962, "Buritinópolis", "buritinopolense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5204003, "Cabeceiras", "cabeceirense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5204102, "Cachoeira Alta", "cachoeira-altense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5204201, "Cachoeira de Goiás", "cachoeirense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5204250, "Cachoeira Dourada", "cachoeirense-do-sul", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5204300, "Caçu", "caçuense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5204409, "Caiapônia", "caiaponiense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5204508, "Caldas Novas", "caldense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5204557, "Caldazinha", "caldazinhense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5204607, "Campestre de Goiás", "campestrino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5204656, "Campinaçu", "campinaçuense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5204706, "Campinorte", "campinortense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5204805, "Campo Alegre de Goiás", "campo-alegrense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5204854, "Campo Limpo de Goiás", "campolimpense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5204904, "Campos Belos", "campo-belense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5204953, "Campos Verdes", "campo-verdense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5205000, "Carmo do Rio Verde", "carmo-rio-verdino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5205059, "Castelândia", "castelandense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5205109, "Catalão", "catalano", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5205208, "Caturaí", "caturaiense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5205307, "Cavalcante", "cavalcantense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5205406, "Ceres", "ceresino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5205455, "Cezarina", "cezarinense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5205471, "Chapadão do Céu", "chapadense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5205497, "Cidade Ocidental", "ocidentalense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5205513, "Cocalzinho de Goiás", "cocalzinhense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5205521, "Colinas do Sul", "colinense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5205703, "Córrego do Ouro", "corregorino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5205802, "Corumbá de Goiás", "corumbaense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5205901, "Corumbaíba", "corumbaibense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5206206, "Cristalina", "cristalinense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5206305, "Cristianópolis", "cristianopolino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5206404, "Crixás", "crixasense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5206503, "Cromínia", "crominiense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5206602, "Cumari", "cumarino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5206701, "Damianópolis", "damianopolino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5206800, "Damolândia", "damolandense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5206909, "Davinópolis", "davinopolino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5207105, "Diorama", "dioramense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5208301, "Divinópolis de Goiás", "divinopolino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5207253, "Doverlândia", "doverlandense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5207352, "Edealina", "edealinense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5207402, "Edéia", "edeiense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5207501, "Estrela do Norte", "estrela-nortense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5207535, "Faina", "fainense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5207600, "Fazenda Nova", "fazenda-novense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5207808, "Firminópolis", "firminopolense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5207907, "Flores de Goiás", "florense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5208004, "Formosa", "formosense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5208103, "Formoso", "formosense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5208152, "Gameleira de Goiás", "gameleirense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5208400, "Goianápolis", "goianapolino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5208509, "Goiandira", "goiandirense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5208608, "Goianésia", "goianesiense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5208707, "Goiânia", "goianiense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5208806, "Goianira", "goianirense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5208905, "Goiás", "goiano", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5209101, "Goiatuba", "goiatubense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5209150, "Gouvelândia", "gouvelandense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5209200, "Guapó", "guapoense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5209291, "Guaraíta", "guaraitense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5209408, "Guarani de Goiás", "guaraniense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5209457, "Guarinos", "guarinense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5209606, "Heitoraí", "heitoraiense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5209705, "Hidrolândia", "hidrolandense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5209804, "Hidrolina", "hidrolinense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5209903, "Iaciara", "iaciarense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5209937, "Inaciolândia", "inaciolandense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5209952, "Indiara", "indiarense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5210000, "Inhumas", "inhumense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5210109, "Ipameri", "ipamerino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5210158, "Ipiranga de Goiás", "ipiranguense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5210208, "Iporá", "iporaense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5210307, "Israelândia", "israelandense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5210406, "Itaberaí", "itaberino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5210562, "Itaguari", "itaguarino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5210604, "Itaguaru", "itaguaruense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5210802, "Itajá", "itajaense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5210901, "Itapaci", "itapacino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5211008, "Itapirapuã", "itapirapuano", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5211206, "Itapuranga", "itapuranguense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5211305, "Itarumã", "itarumaense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5211404, "Itauçu", "itauçuense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5211503, "Itumbiara", "itumbiarense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5211602, "Ivolândia", "ivolandense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5211701, "Jandaia", "jandaiense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5211800, "Jaraguá", "jaraguense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5211909, "Jataí", "jataiense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5212006, "Jaupaci", "jaupacino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5212055, "Jesúpolis", "jesupolino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5212105, "Joviânia", "jovianiense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5212204, "Jussara", "jussariano", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5212253, "Lagoa Santa", "lagosentense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5212303, "Leopoldo de Bulhões", "leopoldense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5212501, "Luziânia", "luzianiense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5212600, "Mairipotaba", "mairipotabense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5212709, "Mambaí", "mambaiense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5212808, "Mara Rosa", "mara-rosense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5212907, "Marzagão", "marzagonense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5212956, "Matrinchã", "matrinchaense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5213004, "Maurilândia", "maurilandense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5213053, "Mimoso de Goiás", "mimosense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5213087, "Minaçu", "minaçuense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5213103, "Mineiros", "mineirense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5213400, "Moiporá", "moiporaense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5213509, "Monte Alegre de Goiás", "monte-alegrense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5213707, "Montes Claros de Goiás", "montes-clarense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5213756, "Montividiu", "montividiuense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5213772, "Montividiu do Norte", "montividense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5213806, "Morrinhos", "morrinhense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5213855, "Morro Agudo de Goiás", "morro-agudense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5213905, "Mossâmedes", "mossamedino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5214002, "Mozarlândia", "mozarlandense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5214051, "Mundo Novo", "mundo-novense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5214101, "Mutunópolis", "mutunopolino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5214408, "Nazário", "nazarinense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5214507, "Nerópolis", "neropolino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5214606, "Niquelândia", "niquelandense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5214705, "Nova América", "nova-americano", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5214804, "Nova Aurora", "nova-aurorense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5214838, "Nova Crixás", "nova-crixaense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5214861, "Nova Glória", "nova-glorino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5214879, "Nova Iguaçu de Goiás", "nova iguaçuense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5214903, "Nova Roma", "nova-romano", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5215009, "Nova Veneza", "nova-venezino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5215207, "Novo Brasil", "novo-brasilense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5215231, "Novo Gama", "novo-gamense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5215256, "Novo Planalto", "planaltense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5215306, "Orizona", "orizonense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5215405, "Ouro Verde de Goiás", "ouro-verdense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5215504, "Ouvidor", "ouvidorense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5215603, "Padre Bernardo", "padre-bernardense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5215652, "Palestina de Goiás", "palestinense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5215702, "Palmeiras de Goiás", "palmeirense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5215801, "Palmelo", "palmelino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5215900, "Palminópolis", "palminopolino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5216007, "Panamá", "panamenho", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5216304, "Paranaiguara", "paranaiguarense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5216403, "Paraúna", "paraunense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5216452, "Perolândia", "perolandense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5216809, "Petrolina de Goiás", "petrolinense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5216908, "Pilar de Goiás", "pilarense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5217104, "Piracanjuba", "piracanjubense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5217203, "Piranhas", "piranhense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5217302, "Pirenópolis", "pirenopolino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5217401, "Pires do Rio", "piresino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5217609, "Planaltina", "planaltinense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5217708, "Pontalina", "pontalinense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5218003, "Porangatu", "porangatuense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5218052, "Porteirão", "porteirense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5218102, "Portelândia", "portelandense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5218300, "Posse", "possense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5218391, "Professor Jamil", "jamilense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5218508, "Quirinópolis", "quirinopolino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5218607, "Rialma", "rialmense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5218706, "Rianápolis", "rianapolino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5218789, "Rio Quente", "rio-quentense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5218805, "Rio Verde", "rio-verdense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5218904, "Rubiataba", "rubiatabense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5219001, "Sanclerlândia", "sanclerlandense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5219100, "Santa Bárbara de Goiás", "santa-barbarense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5219209, "Santa Cruz de Goiás", "santa-cruzano", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5219258, "Santa Fé de Goiás", "santa-feense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5219308, "Santa Helena de Goiás", "santa-helenense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5219357, "Santa Isabel", "santa-isabelense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5219407, "Santa Rita do Araguaia", "santa-ritense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5219456, "Santa Rita do Novo Destino", "santaritense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5219506, "Santa Rosa de Goiás", "santa-rosense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5219605, "Santa Tereza de Goiás", "santerezino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5219704, "Santa Terezinha de Goiás", "terezinhense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5219712, "Santo Antônio da Barra", "santatoniense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5219738, "Santo Antônio de Goiás", "santoantoniense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5219753, "Santo Antônio do Descoberto", "descobertense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5219803, "São Domingos", "dominicano", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5219902, "São Francisco de Goiás", "franciscano", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5220058, "São João da Paraúna", "joanino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5220009, "São João d'Aliança", "são-joanense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5220108, "São Luís de Montes Belos", "monte-belense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5220157, "São Luíz do Norte", "são-luizense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5220207, "São Miguel do Araguaia", "são-miguelense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5220264, "São Miguel do Passa Quatro", "passa-quatrense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5220280, "São Patrício", "sampatriciense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5220405, "São Simão", "canalense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5220454, "Senador Canedo", "canedense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5220504, "Serranópolis", "serranopolino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5220603, "Silvânia", "silvaniense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5220686, "Simolândia", "simolandense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5220702, "Sítio d'Abadia", "sitiense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5221007, "Taquaral de Goiás", "taquaralense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5221080, "Teresina de Goiás", "teresinense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5221197, "Terezópolis de Goiás", "terezopolino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5221304, "Três Ranchos", "triranchense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5221403, "Trindade", "trindadense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5221452, "Trombas", "trombense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5221502, "Turvânia", "turvaniense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5221551, "Turvelândia", "turvelandense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5221577, "Uirapuru", "uirapuruense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5221601, "Uruaçu", "uruaçuense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5221700, "Uruana", "uruanense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5221809, "Urutaí", "urutaíno", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5221858, "Valparaíso de Goiás", "valparaisense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5221908, "Varjão", "varjãoense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5222005, "Vianópolis", "vianopolino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5222054, "Vicentinópolis", "vicentinopolino", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5222203, "Vila Boa", "vilaboense", 52);
INSERT INTO municipalities(code, name, gentilic, state) VALUES (5222302, "Vila Propício", "propiciense", 52);